{
 "title": "Services / Cluster Autoscaler (AWS)",
 "description": "Overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus. https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [
  "prometheus",
  "AWS",
  "Autoscaler"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\"})\n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "gauge",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\", cluster=\"$cluster\"})/sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "stat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster=\"$cluster\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Cluster direction?",
   "type": "stat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster=\"$cluster\"})-sum(cluster_autoscaler_scaled_down_nodes_total{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{cluster=\"$cluster\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\"})\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Node scale up/down activity",
   "type": "timeseries",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "round(sum(increase(cluster_autoscaler_scaled_up_nodes_total{cluster=\"$cluster\"}[5m])), 1)",
     "legendFormat": "scale_up"
    },
    {
     "expr": "round(sum(increase(cluster_autoscaler_scaled_down_nodes_total{cluster=\"$cluster\"}[5m])), 1)",
     "legendFormat": "scale_down"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "timeseries",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\", cluster=\"$cluster\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\", cluster=\"$cluster\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\", cluster=\"$cluster\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Cluster Resources",
   "type": "timeseries",
   "description": "Shows the total number of CPU core and Memory in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_cpu_current_cores{cluster=\"$cluster\"})",
     "legendFormat": "Total CPU"
    },
    {
     "expr": "sum(cluster_autoscaler_cluster_memory_current_bytes{cluster=\"$cluster\"}/1024/1024/1024)",
     "legendFormat": "Total Memory (GB)"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "timeseries",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cluster_autoscaler_evicted_pods_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster=\"$cluster\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  }
 ]
}