{
 "title": "Services / Cluster Upgrades",
 "description": "Cost metrics from the Kubecost product",
 "tags": [
  "cost",
  "utilization",
  "metrics"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cloud",
    "label": "Cloud",
    "query": {
     "query": "label_values(kube_node_status_capacity{}, cloud)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_capacity{cloud=~\"$cloud\"}, cluster)"
    }
   },
   { "name": "timeRange", "query": "1h,6h,12h,1d,7d,14d,30d,90d" },
   {
    "name": "localStorageGBCost",
    "label": "Cost per Gb hour for attached disks",
    "query": ".14"
   },
   { "name": "percentEgress", "query": ".1" },
   { "name": "egressCost", "query": ".12" }
  ]
 },
 "panels": [
  {
   "title": "Cognigy Products Versions",
   "type": "table",
   "description": "Cognigy Products versions",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (cluster, git_version, cloud, region, releaseVersion) (cognigy_ai_release_version{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (cluster, git_version, cloud, region, version) (cognigy_vg_version{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cognigy Product Upgrades",
   "type": "state-timeline",
   "description": "Timeline of Cognigy Product Upgrades",
   "gridPos": { "h": 83, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg by (cluster, cloud, releaseVersion) (cognigy_ai_release_version{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}: AI v{{releaseVersion}}"
    },
    {
     "expr": "avg by (cluster, cloud, version) (cognigy_vg_version{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}: VG v{{version}}"
    }
   ]
  },
  {
   "title": "Kubernetes Upgrades",
   "type": "state-timeline",
   "description": "Timeline of data plane (kubelet) upgrades of Kubernetes clusters",
   "gridPos": { "h": 83, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg by (cluster, git_version) (kubernetes_build_info{cloud=~\"$cloud\", cluster=~\"$cluster\", job=\"kubelet\"})",
     "legendFormat": "{{cluster}}: {{git_version}}"
    }
   ]
  },
  {
   "title": "Kubernetes Versions",
   "type": "table",
   "description": "Kubernetes data plane versions",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (cluster, git_version, cloud, region) (kubernetes_build_info{cloud=~\"$cloud\", cluster=~\"$cluster\", job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}