{
 "title": "Container Health",
 "tags": [ "k8s" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment replicas available",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$namespace\"}) / sum(kube_deployment_status_replicas{namespace=\"$namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod phase not running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Unknown|Pending|Failed\"}) "
    }
   ]
  },
  {
   "title": "Container waiting total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod container restart (in 12h)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} - kube_pod_container_status_restarts_total{namespace=\"$namespace\"} offset 12h)"
    }
   ]
  },
  {
   "title": "Job active",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Job failed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment replica unavailable",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"$namespace\"} >= 0",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pod container waiting reason",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\"}  >= 0",
     "legendFormat": "{{container}} | {{pod}} | {{reason}}"
    }
   ]
  },
  {
   "title": "Container restarts (OOMKilled)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", namespace=\"$namespace\"}) by (container)) - (sum (kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", namespace=\"$namespace\"} offset 5m) by (container)) > 0",
     "legendFormat": "{{container}} "
    }
   ]
  },
  {
   "title": "Container restarts (Error)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum (kube_pod_container_status_last_terminated_reason{reason=\"Error\", namespace=\"$namespace\"}) by (container)) - (sum (kube_pod_container_status_last_terminated_reason{reason=\"Error\", namespace=\"$namespace\"} offset 5m) by (container)) > 0",
     "legendFormat": "{{container}} "
    }
   ]
  },
  {
   "title": "Container restart count",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"} > 0)  by (container, pod)"
    }
   ]
  }
 ]
}