{
 "title": "Services / Kubecost Global v2",
 "description": "Cost metrics from the Kubecost product",
 "tags": [
  "cost",
  "utilization",
  "metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "timeRange", "query": "1h,6h,12h,1d,7d,14d,30d,90d" },
   {
    "name": "localStorageGBCost",
    "label": "Cost per Gb hour for attached disks",
    "query": ".14"
   },
   { "name": "percentEgress", "query": ".1" },
   { "name": "egressCost", "query": ".12" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cloud",
    "query": {
     "query": "label_values(kube_node_status_capacity{}, cloud)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_capacity{cloud=~\"$cloud\"}, cluster)"
    }
   },
   {
    "name": "non_default_nodes",
    "label": "non_default_nodes",
    "query": {
     "query": "label_values(kube_node_spec_taint{cluster=~\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Cloud Costs ($)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubecost:compute_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (cluster) (kubecost:memory_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum by (cluster) (kubecost:storage_pv_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cluster) (kubecost:storage_local_gb:total{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * $localStorageGBCost",
     "legendFormat": "Storage"
    },
    {
     "expr": "kubernetes_build_info{cloud=~\"$cloud\", cluster=~\"$cluster\"}",
     "legendFormat": "Version"
    }
   ]
  },
  {
   "title": "Cluster Spare Capacity",
   "type": "table",
   "description": "Unused nodes in the default pool",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster) (kube_node_info{node!~\"$non_default_nodes\", cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "Default Nodes"
    },
    {
     "expr": "sum by (cluster) (kube_node_info{node=~\"$non_default_nodes\", cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "Non-default Nodes"
    },
    {
     "expr": "(sum by (cluster)(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\", cloud=~\"$cloud\", cluster=~\"$cluster\", node!~\"$non_default_nodes\"}) - sum by (cluster) (max by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\",  cloud=~\"$cloud\", cluster=~\"$cluster\", node!~\"$non_default_nodes\"}) * on(cluster, namespace, pod) group_left() max by (cluster,namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1)))/max by (cluster)(kube_node_status_capacity{job=\"kube-state-metrics\",resource=\"cpu\", cloud=~\"$cloud\", cluster=~\"$cluster\", node!~\"$non_default_nodes\"})",
     "legendFormat": "Free CPU Default"
    },
    {
     "expr": "(sum by (cluster)(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\", cloud=~\"$cloud\", cluster=~\"$cluster\", node!~\"$non_default_nodes\"}) - sum by (cluster) (max by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\",  cloud=~\"$cloud\", cluster=~\"$cluster\", node!~\"$non_default_nodes\"}) * on(cluster, namespace, pod) group_left() max by (cluster,namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1)))/max by (cluster)(kube_node_status_capacity{job=\"kube-state-metrics\",resource=\"memory\", cloud=~\"$cloud\", cluster=~\"$cluster\", node!~\"$non_default_nodes\"})",
     "legendFormat": "Free RAM Default"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "timeseries",
   "description": "Sum of compute, memory, and storage costs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubecost:compute_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cluster) (kubecost:memory_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cluster) (kubecost:storage_pv_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cluster) (kubecost:storage_local_gb:total{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * $localStorageGBCost",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Total Daily Cloud Costs",
   "type": "timeseries",
   "description": "Total Costs per Cloud Provider",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (cloud) (kubecost:compute_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cloud) (kubecost:memory_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cloud) (kubecost:storage_pv_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cloud) (kubecost:storage_local_gb:total{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * $localStorageGBCost",
     "legendFormat": "{{ cloud }}"
    }
   ]
  },
  {
   "title": "Compute Cost",
   "type": "timeseries",
   "description": "Monthly run rate of CPU + GPU costs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubecost:compute_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Cost",
   "type": "timeseries",
   "description": "Monthly run rate of memory costs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubecost:memory_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})",
     "legendFormat": "{{ cluster }} "
    }
   ]
  },
  {
   "title": "Storage Cost",
   "type": "timeseries",
   "description": "Monthly run rate of attached disk + PV storage costs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubecost:storage_pv_cost:monthly_usd{cloud=~\"$cloud\", cluster=~\"$cluster\"})\n+\nsum by (cluster) (kubecost:storage_local_gb:total{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * $localStorageGBCost",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}