{
 "title": "Kubecost Global",
 "description": "Cost metrics from the Kubecost product",
 "tags": [
  "cost",
  "utilization",
  "metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeRange", "query": "1h,6h,12h,1d,7d,14d,30d,90d" },
   {
    "name": "localStorageGBCost",
    "label": "Cost per Gb hour for attached disks",
    "query": ".14"
   },
   { "name": "percentEgress", "query": ".1" },
   { "name": "egressCost", "query": ".12" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cloud",
    "query": {
     "query": "label_values(kube_node_status_capacity{}, cloud)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_capacity{cloud=~\"$cloud\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Cloud Costs ($)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"cpu\", unit=\"core\", cloud=~\"$cloud\", cluster=~\"$cluster\"}) * avg by (node,cluster,cloud) ((node_cpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)) + (avg by (node,cluster,cloud) (node_gpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (cluster) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",cloud=~\"$cloud\", cluster=~\"$cluster\"})/1024/1024/1024* avg by (node,cluster,cloud) ((node_ram_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)))",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum by (cluster) ( (avg(pv_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) * 730 * avg(kube_persistentvolume_capacity_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) / 1024 / 1024 / 1024 ))\n+\nsum by (cluster) (node_filesystem_size_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\", job=\"node-exporter\", fstype!=\"\", fstype!=\"tmpfs\", fstype!=\"nfs4\"}) /1024 /1024 /1024 * $localStorageGBCost",
     "legendFormat": "Storage"
    },
    {
     "expr": "kubernetes_build_info{cloud=~\"$cloud\", cluster=~\"$cluster\"}",
     "legendFormat": "Version"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "graph",
   "description": "Sum of compute, memory, and storage costs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"cpu\", unit=\"core\", cloud=~\"$cloud\", cluster=~\"$cluster\"}) * avg by (node,cluster,cloud) ((node_cpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)) + (avg by (node,cluster,cloud) (node_gpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730))\n+\nsum by (cluster) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",cloud=~\"$cloud\" , cluster=~\"$cluster\"})/1024/1024/1024* avg by (node,cluster,cloud) ((node_ram_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)))\n+\nsum by (cluster) ( (avg(pv_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) * 730 * avg(kube_persistentvolume_capacity_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) / 1024 / 1024 / 1024 ))\n+\nsum by (cluster) (node_filesystem_size_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\", job=\"node-exporter\", fstype!=\"\", fstype!=\"tmpfs\", fstype!=\"nfs4\"}) /1024 /1024 /1024 * $localStorageGBCost",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Total Daily Cloud Costs",
   "type": "graph",
   "description": "Total Costs per Cloud Provider",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum by (cloud) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"cpu\", unit=\"core\", cloud=~\"$cloud\", cluster=~\"$cluster\"}) * avg by (node,cluster,cloud) ((node_cpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)) + (avg by (node,cluster,cloud) (node_gpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730))\n+\nsum by (cloud) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",cloud=~\"$cloud\" , cluster=~\"$cluster\"})/1024/1024/1024* avg by (node,cluster,cloud) ((node_ram_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)))\n+\nsum by (cloud) ((avg(pv_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) * 730 * avg(kube_persistentvolume_capacity_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) / 1024 / 1024 / 1024 ))\n+\nsum by (cloud) (node_filesystem_size_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\", job=\"node-exporter\", fstype!=\"\", fstype!=\"tmpfs\", fstype!=\"nfs4\"}) /1024 /1024 /1024 * $localStorageGBCost",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Compute Cost",
   "type": "graph",
   "description": "Monthly run rate of CPU + GPU costs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"cpu\", unit=\"core\", cloud=~\"$cloud\", cluster=~\"$cluster\"}) * avg by (node,cluster,cloud) ((node_cpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)) + (avg by (node,cluster,cloud) (node_gpu_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Cost",
   "type": "graph",
   "description": "Monthly run rate of memory costs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) ((avg by (node,cluster,cloud) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",cloud=~\"$cloud\" , cluster=~\"$cluster\"})/1024/1024/1024* avg by (node,cluster,cloud) ((node_ram_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) * 730)))",
     "legendFormat": "{{ cluster }} "
    }
   ]
  },
  {
   "title": "Storage Cost",
   "type": "graph",
   "description": "Monthly run rate of attached disk + PV storage costs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) ( (avg(pv_hourly_cost{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) * 730 * avg(kube_persistentvolume_capacity_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\"}) by (persistentvolume,cluster,cloud) / 1024 / 1024 / 1024 ))\n+\nsum by (cluster) (node_filesystem_size_bytes{cloud=~\"$cloud\", cluster=~\"$cluster\", job=\"node-exporter\", fstype!=\"\", fstype!=\"tmpfs\", fstype!=\"nfs4\"}) /1024 /1024 /1024 * $localStorageGBCost",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}