{
 "title": "Services / Qdrant",
 "description": "A quick and simple dashboard for viewing how your qdrant is doing.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\"qdrant-.*\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Qdrant version",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_info{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "collections_total{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total vectors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "collections_vector_total{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rest_responses_avg_duration_seconds{cluster=\"$cluster\"})",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Pending operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cluster_pending_operations_total{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "200 REST responses/min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_responses_total{cluster=\"$cluster\", status=\"200\", endpoint=\"/collections/{name}/points/search\"}[1m]))",
     "legendFormat": "200"
    }
   ]
  },
  {
   "title": "4xx REST responses/min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_responses_total{cluster=\"$cluster\",status=~\"4.*\"}[1m]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"$volume\"})))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"$volume\"})))\n)\n",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=\"$volume\"})))\n",
     "legendFormat": "Free Space"
    }
   ]
  }
 ]
}