{
 "title": "Services / RabbitMQ Detailed",
 "description": "A dashboard that monitors RabbitMQ detailed metrics.",
 "tags": [
  "rabbitmq",
  "rabbitmq-detailed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "RabbitMQ Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", namespace=\"$namespace\"},rabbitmq_cluster)"
    }
   },
   {
    "name": "vhost",
    "label": "Virtual Host",
    "query": {
     "query": "query_result(rabbitmq_detailed_queue_info{cluster=\"$cluster\"}  * on(instance, job, pod, namespace, container, endpoint) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\"})"
    }
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "query_result(rabbitmq_detailed_queue_info{cluster=\"$cluster\", vhost=~\"$vhost\"}  * on(instance, job, pod, namespace, container, endpoint) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  rabbitmq_detailed_queue_consumers{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\"}\n  * on(instance, job, endpoint, namespace, container) group_left(rabbitmq_cluster) \n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\"}\n)"
    }
   ]
  },
  {
   "title": "Queues with Messages Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  rabbitmq_detailed_queue_messages_ready{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\"}\n  * on(instance, job, endpoint, namespace, container) group_left(rabbitmq_cluster)\n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"} > 0\n  )\n"
    }
   ]
  },
  {
   "title": "Queues with Messages Unacked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  rabbitmq_detailed_queue_messages_unacked{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\"}\n  * on(instance, job, endpoint, namespace, container) group_left(rabbitmq_cluster) \n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"} > 0\n  )"
    }
   ]
  },
  { "title": "Virtual Host Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Virtual Host Ready & Unacked Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, vhost)(\n  rabbitmq_detailed_queue_messages_ready{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\"}\n  * on(instance, job)\n  group_left(rabbitmq_cluster, rabbitmq_node)\n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Ready - {{ vhost }}"
    },
    {
     "expr": "sum by (instance, vhost)(\n  rabbitmq_detailed_queue_messages_unacked{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\"}\n  * on(instance, job)\n  group_left(rabbitmq_cluster, rabbitmq_node)\n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Unacked - {{ vhost }}"
    }
   ]
  },
  { "title": "Queue Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Queue Length & Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (instance, vhost, queue) (\n  rabbitmq_detailed_queue_consumers{cluster=\"$cluster\", vhost=~\"$vhost\", namespace=\"$namespace\", queue=~\"$queue\", queue!~\"^amq\\\\.gen-.*|^rpc-callback-.*\"}\n  * on(instance, job, endpoint, namespace, container) \n  group_left(rabbitmq_cluster, rabbitmq_node) \n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)"
    },
    {
     "expr": "sum by (instance, vhost, queue) (\n  rabbitmq_detailed_queue_messages{cluster=\"$cluster\", vhost=~\"$vhost\", namespace=\"$namespace\", queue=~\"$queue\", queue!~\"^amq\\\\.gen-.*|^rpc-callback-.*\"}\n  * on(instance, job, endpoint, namespace, container) \n  group_left(rabbitmq_cluster, rabbitmq_node) \n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)"
    }
   ]
  },
  {
   "title": "Queue Ready Messages",
   "type": "timeseries",
   "description": "Messages ready to be delivered to consumers.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, vhost, queue)(\n  rabbitmq_detailed_queue_messages_ready{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\", queue!~\"^amq\\\\.gen-.*|^rpc-callback-.*\"}\n  * on(instance, job)\n  group_left(rabbitmq_cluster, rabbitmq_node) \n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "{{ queue }} - {{ vhost }}"
    }
   ]
  },
  {
   "title": "Queue Unacked Messages",
   "type": "timeseries",
   "description": "Messages delivered to consumers but not yet acknowledged.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, vhost, queue)(\n  rabbitmq_detailed_queue_messages_unacked{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\", queue!~\"^amq\\\\.gen-.*|^rpc-callback-.*\"}\n  * on(instance, job)\n  group_left(rabbitmq_cluster, rabbitmq_node) \n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "{{ queue }} - {{ vhost }}"
    }
   ]
  },
  {
   "title": "Queue Total Messages",
   "type": "timeseries",
   "description": "Sum of ready and unacknowledged messages - total queue depth.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, vhost, queue)(\n  rabbitmq_detailed_queue_messages{cluster=\"$cluster\", namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\", queue!~\"^amq\\\\.gen-.*|^rpc-callback-.*\"}\n  * on(instance, job)\n  group_left(rabbitmq_cluster, rabbitmq_node)\n  rabbitmq_identity_info{rabbitmq_endpoint=\"detailed\", cluster=\"$cluster\", rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "{{ queue }} - {{ vhost }}"
    }
   ]
  }
 ]
}