{
 "title": "Redis Instances Overview",
 "description": "Redis Instances Overview",
 "tags": [
  "prometheus",
  "redis",
  "redis-ha"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": {
     "query": "label_values(redis_up{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod_name\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\", cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\", cluster=\"$cluster\"} / redis_memory_max_bytes{instance=~\"$instance\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\", cluster=\"$cluster\"}[1m])",
     "legendFormat": "commands, {{ instance }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\", cluster=\"$cluster\"} ",
     "legendFormat": "used, {{ instance }}"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\", cluster=\"$cluster\"} ",
     "legendFormat": "max, {{ instance }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "input, {{ instance }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "output, {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\", cluster=\"$cluster\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\", cluster=\"$cluster\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\", cluster=\"$cluster\"}) ",
     "legendFormat": "not expiring, {{ instance }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\", cluster=\"$cluster\"}) ",
     "legendFormat": "expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\", cluster=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\", cluster=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Top Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\", cluster=\"$cluster\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Redis Connected/Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=~\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance =~ \"$instance\", cluster=\"$cluster\"}[1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance =~ \"$instance\", cluster=\"$cluster\"}[1m])) by (cmd) / sum(irate(redis_commands_total{instance =~ \"$instance\", cluster=\"$cluster\"}[1m])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=~\"$instance\", cluster=\"$cluster\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}