{
 "title": "Services / Traefik",
 "description": "Traefik dashboard prometheus",
 "tags": [ "traefik" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(traefik_config_reloads_total{cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "percentiles", "query": "95,99,80,50" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Traefik instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{cluster=\"$cluster\", namespace=\"$namespace\",condition=\"true\",pod=~\"traefik.*\"})"
    }
   ]
  },
  {
   "title": "Global latency $percentiles% over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", code=\"200\",method=\"GET\"}[5m])) by (le))",
     "legendFormat": "Latency over 1 min"
    }
   ]
  },
  {
   "title": "Per node latency $percentiles% over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\",code=\"200\",method=\"GET\"}[5m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total requests over 1min per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (service)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Frontends (entrypoints)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Connections (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Open Connections (by method)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{cluster=\"$cluster\", namespace=\"$namespace\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score (over 5 min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\",le=\"0.1\",code=\"200\"}[5m])) by (job) / sum(rate(traefik_entrypoint_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\",code=\"200\"}[5m])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "HTTP Codes  stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status code 2xx over 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"2.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (method, code)",
     "legendFormat": "{{ method }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Status code 3xx over 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{cluster=\"$cluster\", namespace=\"$namespace\",code=~\"3..\"}[1m])) by (method, code)",
     "legendFormat": "{{ method }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Status code 4xx over 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"4.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (method, code)",
     "legendFormat": "{{ method }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Status code 5xx over 1min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"5.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (method, code)",
     "legendFormat": "{{ method }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Status code 2xx by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"2.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (service, code)",
     "legendFormat": "{{ service }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Status code 3xx by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{cluster=\"$cluster\", namespace=\"$namespace\",code!~\"2..|5..|4..\"}[1m])) by (service ,code)",
     "legendFormat": "{{ service }} : {{ code }}"
    }
   ]
  },
  {
   "title": "Status code 4xx by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"4.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (service ,code)",
     "legendFormat": "{{ service }} : {{ code}}"
    }
   ]
  },
  {
   "title": "Status code 5xx by service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=~\"5.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (service ,code)",
     "legendFormat": "{{ service }} : {{ code}}"
    }
   ]
  }
 ]
}