---
rbac:
  ## Disable deprecated PodSecurityPolicy
  pspEnabled: false

serviceMonitor:
  enabled: true
  relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: instance
      regex: (.*redis.*)
      replacement: "redis"

# referenced via service
redisAddress: redis://redis:6379

auth:
  # Use password authentication
  enabled: true
  # Use existing secret (ignores redisPassword)
  secret:
    name: "cognigy-redis-password"
    key: "REDIS_PASSWORD"