{
 "title": "FluxCD / Flux Overview Global",
 "tags": [ "flux" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "operator_namespace",
    "query": {
     "query": "label_values(gotk_reconcile_duration_seconds_sum{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_resource_info{cluster=~\"$cluster\"},exported_namespace)"
    }
   },
   {
    "name": "customresource_kind",
    "label": "Resource Type",
    "query": {
     "query": "label_values(gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\"},customresource_kind)"
    }
   },
   {
    "name": "customresource_name",
    "label": "Name",
    "query": {
     "query": "label_values(gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status for ${customresource_kind:raw} Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "customresource_kind"
  },
  {
   "title": "Total ${customresource_kind:raw}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\", name=~\"$customresource_name\"})"
    }
   ]
  },
  {
   "title": "Ready ${customresource_kind:raw}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\", name=~\"$customresource_name\", ready=\"True\"})"
    }
   ]
  },
  {
   "title": "Failing ${customresource_kind:raw}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\", name=~\"$customresource_name\", ready=\"False\"})"
    }
   ]
  },
  {
   "title": "Suspended ${customresource_kind:raw}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\", name=~\"$customresource_name\", suspended=\"true\"})"
    }
   ]
  },
  {
   "title": "Suspended Objects",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\", name=~\"$customresource_name\", suspended=\"true\"}"
    }
   ]
  },
  {
   "title": "${customresource_kind:raw} reconciliation status",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=~\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"$customresource_kind\", name=~\"$customresource_name\"}"
    }
   ]
  }
 ]
}