{
 "title": "FluxCD / Flux Cluster Stats",
 "tags": [ "flux" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "operator_namespace",
    "query": {
     "query": "label_values(gotk_reconcile_duration_seconds_sum, namespace)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_resource_info,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\"})"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\", ready=\"False\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Manifests Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"})"
    }
   ]
  },
  {
   "title": "Failing Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\", ready=\"False\"})"
    }
   ]
  },
  {
   "title": "Suspended Resources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"Alert|Kustomization|HelmRelease|GitRepository|HelmRepository|Bucket|OCIRepository\", suspended=\"true\"})"
    }
   ]
  },
  {
   "title": "Reconciler ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Source ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}[5m])) by (kind)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Suspended Objects",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", suspended=\"true\"}"
    }
   ]
  },
  {
   "title": "HelmRelease reconciliation status",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"HelmRelease\"}"
    }
   ]
  },
  {
   "title": "Kustomization reconciliation readiness ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"Kustomization\"}"
    }
   ]
  },
  {
   "title": "Source acquisition readiness ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}"
    }
   ]
  },
  {
   "title": "Alert readiness ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "gotk_resource_info{cluster=\"$cluster\", exported_namespace=~\"$namespace\", customresource_kind=~\"Alert\"}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Cluster reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name)",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  },
  {
   "title": "Source acquisition duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}[5m])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\"}[5m])) by (kind, name)",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  }
 ]
}