{{- $targetNamespace := .Values.appNamespacesTarget }}
{{- if .Values.rules.la.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-cognigy-la-rules
  labels:
    {{- include "cognigy-monitors.labels" . | nindent 4 }}
spec:
  groups:
    - name: cognigy.la.alert.HighHttpErrorRate
      rules:
    {{- if (.Values.rules.la.HighHttpErrorRate.enabled ) }}
      - alert: LiveAgentHighHttpErrorRate
        expr: 100 * (sum(increase(ruby_http_requests_total{controller=~"api/v1/accounts/.*", status!~"2..|3..|404|401|412"}[5m])) by (action, controller, status)) /
              (sum(increase(ruby_http_requests_total{controller=~"api/v1/accounts/.*"}[5m])) by (action, controller, status))
              > {{ $.Values.rules.la.HighHttpErrorRate.threshold }}
        for: 15m
        labels:
          severity: warning
          group: la-custom-alert-rules
        annotations:
          summary: LiveAgent HTTP error rate is high (instance {{`{{`}} $labels.instance }})
          description: "LiveAgent HTTP error rate is above {{ $.Values.rules.la.HighHttpErrorRate.threshold }}%\n  VALUE = {{`{{`}} $value }}\n  LABELS = {{`{{`}} $labels }}"
    {{- end }}
    {{- if (.Values.rules.la.EndpointSlowRequest.enabled ) }}
      - alert: LiveAgentEndpointSlowRequest
        expr: avg (ruby_http_request_duration_seconds{controller=~'api/v1/accounts.*', quantile='0.99'})
              by (controller, action) > {{ $.Values.rules.la.EndpointSlowRequest.threshold }}
        for: 15m
        labels:
          severity: warning
          group: la-custom-alert-rules
        annotations:
          summary: LiveAgent Endpoint requests are slow (endpoint {{`{{`}} $labels.controller }})
          description: "LiveAgent endpoint requests are longer than {{ $.Values.rules.la.EndpointSlowRequest.threshold }}s \n  VALUE = {{`{{`}} $value }}\n  LABELS = {{`{{`}} $labels }}"
    {{- end }}
{{- end -}}