{{- if .Values.rules.sealedSecrets.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-cognigy-sealedsecrets-rules
  labels:
    {{- include "cognigy-monitors.labels" . | nindent 4 }}
spec:
  groups:
  - name: cognigy.alert.sealedsecrets
    rules:
    {{- if .Values.rules.sealedSecrets.sealedSecretNotSynced.enabled }}
    - alert: SealedSecretNotSynced
      expr: sealed_secrets_controller_condition_info{condition="Synced"} == -1
      for: {{ .Values.rules.sealedSecrets.sealedSecretNotSynced.period }}
      labels:
        severity: {{ .Values.rules.sealedSecrets.sealedSecretNotSynced.severity }}
      annotations:
        summary: {{ `Sealed Secret not synced ({{ $labels.namespace }}/{{ $labels.name }})` }}
        description: "SealedSecret '{{`{{`}} $labels.name {{`}}`}}' in namespace '{{`{{`}} $labels.namespace {{`}}`}}' has failed to sync for more than {{ .Values.rules.sealedSecrets.sealedSecretNotSynced.period }}.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}

    {{- if .Values.rules.sealedSecrets.sealedSecretUnsealError.enabled }}
    - alert: SealedSecretUnsealError
      expr: increase(sealed_secrets_controller_unseal_errors_total[10m]) > 0
      for: {{ .Values.rules.sealedSecrets.sealedSecretUnsealError.period }}
      labels:
        severity: {{ .Values.rules.sealedSecrets.sealedSecretUnsealError.severity }}
      annotations:
        summary: {{ `Sealed Secret unseal errors detected (namespace {{ $labels.namespace }})` }}
        description: "The Sealed Secrets controller is encountering unseal errors in namespace '{{`{{`}} $labels.namespace {{`}}`}}' (reason: {{`{{`}} $labels.reason {{`}}`}}) for more than {{ .Values.rules.sealedSecrets.sealedSecretUnsealError.period }}.\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}

    {{- if .Values.rules.sealedSecrets.sealedSecretControllerDown.enabled }}
    - alert: SealedSecretControllerDown
      expr: absent(sealed_secrets_controller_build_info)
      for: {{ .Values.rules.sealedSecrets.sealedSecretControllerDown.period }}
      labels:
        severity: {{ .Values.rules.sealedSecrets.sealedSecretControllerDown.severity }}
      annotations:
        summary: {{ `Sealed Secrets controller is down` }}
        description: "The Sealed Secrets controller has not reported any metrics for more than {{ .Values.rules.sealedSecrets.sealedSecretControllerDown.period }}. The controller may be down or unreachable."
    {{- end }}
{{- end }}
