{{- $targetNamespace := .Values.appNamespacesTarget }}
{{- if .Values.rules.traefik.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-cognigy-traefik-rules
  labels:
    {{- include "cognigy-monitors.labels" . | nindent 4 }}
spec:
  groups:
  - name: cognigy.alert.traefik
    rules:
    {{- if (.Values.rules.traefik.traefikHighHttp4xxErrorRateService.enabled ) }}
    - alert: TraefikHighHttp4xxErrorRateService
      expr: sum(rate(traefik_service_requests_total{code=~"4.*"}[3m])) by (service) / sum(rate(traefik_service_requests_total[3m])) by (service) * 100 > 20
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Traefik high HTTP 4xx error rate service (instance {{`{{`}} $labels.instance }})
        description: "Traefik service 4xx error rate is above 20%\n  VALUE = {{`{{`}} $value }}\n  LABELS = {{`{{`}} $labels }}"
    {{- end }}

    {{- if (.Values.rules.traefik.traefikHighHttp5xxErrorRateService.enabled ) }}
    - alert: TraefikHighHttp5xxErrorRateService
      expr: sum(rate(traefik_service_requests_total{code=~"5.*"}[3m])) by (service) / sum(rate(traefik_service_requests_total[3m])) by (service) * 100 > 5
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Traefik high HTTP 5xx error rate service (instance {{`{{`}} $labels.instance }})
        description: "Traefik service 5xx error rate is above 5%\n  VALUE = {{`{{`}} $value }}\n  LABELS = {{`{{`}} $labels }}"
    {{- end }}

    {{- if (.Values.rules.traefik.traefikOpenConnectionsHigh.enabled ) }}
    - alert: TraefikOpenConnectionsHigh
      expr: >
        (sum (traefik_entrypoint_open_connections) /
        sum (avg_over_time(traefik_entrypoint_open_connections[1d])) > 3) and
        (traefik_entrypoint_open_connections > 500)
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Traefik open connections >3 times higher than the average over last 1 day (instance {{`{{`}} $labels.instance }})
        description: "Traefik open connections higher than the average by:\n  VALUE = {{`{{`}} $value }}\n  LABELS = {{`{{`}} $labels }}"
    {{- end }}

    {{- if (.Values.rules.traefik.traefikTlsCertExpireSoon.enabled ) }}
    - alert: TraefikTlsCertExpireSoon
      expr: (traefik_tls_certs_not_after - time()) < 432000
      for: 6h
      labels:
        severity: warning
      annotations:
        summary: TLS Certificate for (sans {{`{{`}} $labels.sans }}) on (instance {{`{{`}} $labels.instance }}) will expire within the next 5 Days
        description: "TLS Certificate will expire in sec\n  VALUE = {{`{{`}} $value }}\n  LABELS = {{`{{`}} $labels }}"
    {{- end }}

{{- end -}}

