{
 "title": "Thanos / Overview",
 "tags": [ "thanos-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(thanos_status{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instant Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Rate / min",
   "type": "graph",
   "description": "Shows rate of requests against /query for the given time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, handler, code) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query\"}[1m]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests Errors / min",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, code) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query\",code=~\"5..\"}[1m])) / ignoring (code) group_left() sum by (job) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (increase(http_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query\"}[1m])))",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Range Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Rate /min",
   "type": "graph",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, handler, code) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query_range\"}[1m]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests Errors /min",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query_range.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, code) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query_range\",code=~\"5..\"}[1m])) / ignoring (code) group_left() sum by (job) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query_range\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (increase(http_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"query_range\"}[1m])))",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "gRPC (Unary) Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (increase(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", grpc_type=\"unary\"}[1m]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (increase(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"unary\"}[1m])) / ignoring (grpc_code) group_left() sum by (job) (increase(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", grpc_type=\"unary\"}[1m]))"
    }
   ]
  },
  {
   "title": "gRPC Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (increase(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", grpc_type=\"unary\"}[1m])))",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Sidecar",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "gRPC (Unary) Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (increase(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", grpc_type=\"unary\"}[1m]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (increase(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"unary\"}[1m])) / ignoring (grpc_code) group_left() sum by (job) (increase(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", grpc_type=\"unary\"}[1m]))"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (increase(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", grpc_type=\"unary\"}[1m])))",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Receive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Requests Rate",
   "type": "graph",
   "description": "Shows rate of incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, handler, code) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"receive\"}[1m]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Incoming Requests Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job, code) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"receive\",code=~\"5..\"}[1m])) / ignoring (code) group_left() sum by (job) (increase(http_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"receive\"}[1m]))"
    }
   ]
  },
  {
   "title": "Incoming Requests Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (increase(http_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", handler=\"receive\"}[1m])))",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Rule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alert Sent Rate",
   "type": "graph",
   "description": "Shows rate of alerts that successfully sent to alert manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, alertmanager) (rate(thanos_alert_sender_alerts_sent_total{cluster=\"$cluster\", namespace=~\"$namespace\", }[1m]))",
     "legendFormat": "{{alertmanager}}"
    }
   ]
  },
  {
   "title": "Alert Sent Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of sent alerts.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_alert_sender_errors_total{cluster=\"$cluster\", namespace=~\"$namespace\", }[1m])) / sum by (job) (rate(thanos_alert_sender_alerts_sent_total{cluster=\"$cluster\", namespace=~\"$namespace\", }[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Alert Sent Duration",
   "type": "graph",
   "description": "Shows how long has it taken to send alerts to alert manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", }[1m])))",
     "legendFormat": "{{job}} P99"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compaction Rate",
   "type": "graph",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(thanos_compact_group_compactions_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "compaction {{job}}"
    }
   ]
  },
  {
   "title": "Compaction Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(thanos_compact_group_compactions_failures_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[1m])) / sum by (job) (increase(thanos_compact_group_compactions_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  }
 ]
}