{
 "title": "Thanos / Store",
 "tags": [ "thanos-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(thanos_status{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(up{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\".*storegateway.*\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(thanos_status{cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}, pod)"
    }
   },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" }
  ]
 },
 "panels": [
  {
   "title": "gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"unary\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "gRPC (Stream)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Streamed gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Bucket Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of execution for operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operations_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operation_failures_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) / sum by (job, operation) (rate(thanos_objstore_bucket_operations_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{operation}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, operation, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))) * 1",
     "legendFormat": "P99 {{job}}"
    },
    {
     "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operation_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) * 1  / sum by (job, operation) (rate(thanos_objstore_bucket_operation_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (job, operation, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))) * 1",
     "legendFormat": "P50 {{job}}"
    }
   ]
  },
  {
   "title": "Block Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Load Rate",
   "type": "timeseries",
   "description": "Shows rate of block loads from the bucket.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_bucket_store_block_loads_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "block loads"
    }
   ]
  },
  {
   "title": "Block Load Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of block loads from the bucket.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_bucket_store_block_load_failures_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_bucket_store_block_loads_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Block Drop Rate",
   "type": "timeseries",
   "description": "Shows rate of block drops.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, operation) (rate(thanos_bucket_store_block_drops_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "block drops {{job}}"
    }
   ]
  },
  {
   "title": "Block Drop Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of block drops.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_bucket_store_block_drop_failures_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_bucket_store_block_drops_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Show rate of cache requests.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_requests_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of cache hits.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_hits_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Added",
   "type": "timeseries",
   "description": "Show rate of added items to cache.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_items_added_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "timeseries",
   "description": "Show rate of evicted items from cache.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, item_type) (rate(thanos_store_index_cache_items_evicted_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{item_type}}"
    }
   ]
  },
  {
   "title": "Store Sent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chunk Size",
   "type": "timeseries",
   "description": "Shows size of chunks that have sent to the bucket.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by (job) (rate(thanos_bucket_store_sent_chunk_size_bytes_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) / sum by (job) (rate(thanos_bucket_store_sent_chunk_size_bytes_count{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Series Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block queried",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_blocks_queried{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by (job) (rate(thanos_bucket_store_series_blocks_queried_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) / sum by (job) (rate(thanos_bucket_store_series_blocks_queried_count{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_blocks_queried{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Data Fetched",
   "type": "timeseries",
   "description": "Show the size of data fetched",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_data_fetched{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P99: {{data_type}} / {{job}}"
    },
    {
     "expr": "sum by (job, data_type) (rate(thanos_bucket_store_series_data_fetched_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) / sum by (job, data_type) (rate(thanos_bucket_store_series_data_fetched_count{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean: {{data_type}} / {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_data_fetched{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P50: {{data_type}} / {{job}}"
    }
   ]
  },
  {
   "title": "Data Touched",
   "type": "timeseries",
   "description": "Show the size of data touched",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_data_touched{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P99: {{data_type}} / {{job}}"
    },
    {
     "expr": "sum by (job, data_type) (rate(thanos_bucket_store_series_data_touched_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) / sum by (job, data_type) (rate(thanos_bucket_store_series_data_touched_count{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean: {{data_type}} / {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_data_touched{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P50: {{data_type}} / {{job}}"
    }
   ]
  },
  {
   "title": "Result series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_result_series{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by (job) (rate(thanos_bucket_store_series_result_series_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])) / sum by (job) (rate(thanos_bucket_store_series_result_series_count{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_result_series{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Series Operation Durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Get All",
   "type": "timeseries",
   "description": "Shows how long has it taken to get all series.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Merge",
   "type": "timeseries",
   "description": "Shows how long has it taken to merge series.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_bucket_store_series_merge_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_bucket_store_series_merge_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_bucket_store_series_merge_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Gate",
   "type": "timeseries",
   "description": "Shows how long has it taken for a series to wait at the gate.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_bucket_store_series_gate_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_bucket_store_series_gate_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_bucket_store_series_gate_duration_seconds_bucket{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}",
     "legendFormat": "alloc all {{instance}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}",
     "legendFormat": "alloc heap {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[30s])",
     "legendFormat": "alloc rate all {{instance}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}[30s])",
     "legendFormat": "alloc rate heap {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}",
     "legendFormat": "inuse heap {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}",
     "legendFormat": "inuse stack {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\"}",
     "legendFormat": "{{quantile}} {{instance}}"
    }
   ]
  }
 ]
}