apiVersion: v2
name: cognigy-monitoring
description: Cognigy Monitoring Umbrella Chart
type: application
version: 1.1.1

dependencies:
  - name: kube-prometheus-stack
    version: "41.7.3"
    condition: kube-prometheus-stack.enabled
    alias: kubepromstack
  - name: cognigy-monitors
    condition: cognigy-monitors.enabled
    version: 0.1.0
  - name: cognigy-dashboards
    condition: cognigy-dashboards.enabled
    version: 0.2.0
  - name: cognigy-alerts
    condition: cognigy-alerts.enabled
    version: 0.1.0
  - name: prometheus-msteams
    condition: prometheus-msteams.enabled
    version: 1.3.0
  - name: cadvisor
    condition: cadvisor.enabled
    version: 2.2.2