# Target namespace for alerts
appNamespacesTarget: ".*"

# Default Prometheus Runbook URL
runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

# Enable/disable alert rules groups and separate alerts
rules:
  # generic kubernetes alert rules for Cognigy products
  kubernetes:
    enabled: true
    kubePodCrashLooping:
      enabled: true
    kubeDeploymentReplicasMismatch:
      enabled: true
      severity: warning
      timeout: 15m
    kubeStatefulSetReplicasMismatch:
      enabled: true
      severity: warning
      timeout: 15m
    kubePodNotReady:
      enabled: true
      severity: warning
      timeout: 30m
    podManyRestarts:
      enabled: true
      severity: warning
      timeout: 5m
    containerOOMKilled:
      enabled: true
      severity: warning
      timeout: 1m
    cpuThrottlingBackendServiceHigh:
      enabled: true
      severity: warning
      timeout: 15m
    hpaMaxReplicasReached:
      enabled: true
      severity: warning
      timeout: 15m
  # Traefik alert rules
  traefik:
    enabled: true
    traefikHighHttp5xxErrorRateService:
      enabled: true
      # Threshold of 5xx error rate % for traefikHighHttp5xxErrorRateService to start firing
      threshold: 5
    traefikHighHttp4xxErrorRateService:
      enabled: false
    traefikOpenConnectionsHigh:
      enabled: true
    traefikTlsCertExpireSoon:
      enabled: true
  # NGiNX Ingress alert rules (disabled by default)
  nginx:
    enabled: false
    nginxHighHttp5xxErrorRate:
      enabled: true
    nginxHighHttp4xxErrorRate:
      enabled: false
    nginxLatencyHigh:
      enabled: true
    nginxTlsCertExpireSoon:
      enabled: true
  # RabbitMQ alert rules
  rabbitmq:
    enabled: true
  # Redis alert rules
  redis:
    enabled: true
  # MongoDB alert rules
  mongodb:
    enabled: true
    mongodbDown:
      enabled: true
    mongodbReplicaMemberUnhealthy:
      enabled: true
    mongodbReplicationLag:
      enabled: true
      # Threshold of mongodb replica lagging behind (in seconds)
      threshold: 900
    mongodbNumberCursorsOpen:
      enabled: true
    mongodbCursorsTimeouts:
      enabled: true
    mongodbTooManyConnections:
      enabled: true
    mongodbVirtualMemoryUsage:
      enabled: false

  # Cognigy.AI alert rules
  ai:
    enabled: true
    nlpMatcher:
      enabled: true
    functionExecution:
      enabled: true
    serviceExecution:
      enabled: true
    serviceHandover:
      enabled: true
      # threshold on number of errors service handover to trigger alert
      errorsThreshold: 2
    serviceEndpoint:
      enabled: true
      # Message processing Time quantile to analyze
      messageProcessingTimeQuantile: 0.95
      # Threshold (sec) of Message processing Time for EndpointMessageProcessingTimeHigh to start firing
      messageProcessingTimeThreshold: 30
      # Threshold of increase (%) of Message Processing Time for EndpointMessageProcessingTimeIncreasing to start firing
      messageProcessingTimeIncreasingThreshold: 200
      # Baseline for Message processing Time (sec) to avoid false positives of EndpointMessageProcessingTimeIncreasing alert,
      # increases above messageProcessingTimeIncreasingThreshold and with the baseline below messageProcessingTimeBaseline are ignored
      messageProcessingTimeBaseline: 10

  # Cognigy.AI runtime services rules
  runtime:
    enabled: true
    serviceAI:
      enabled: true
    serviceAppSessionManager:
      enabled: true
    serviceExecution:
      enabled: true
    serviceFunctionExecution:
      enabled: true
    serviceHttp:
      enabled: true
    serviceNlpMatcher:
      enabled: true
    servicePlaybookExecution:
      enabled: true
    serviceSessionStateManager:
      enabled: true
  
  vg: 
    enabled: false
    featureServer:
      enabled: true