# Target namespace for alerts
appNamespacesTarget: ".*"

# Default Promethus Runbook URL
runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

# Enable/disable alert rules groups and separate alerts
rules:
  # Cognigy.AI alert rules
  ai:
    enabled: true
    disabled:
      PodManyRestarts: false
      CPUThrottlingBackendServiceHigh: false
      Redis: false
      MongoDb: false
      RabbitMq: false
      NlpMatcher: false
      FunctionExecution: false
      ServiceEndpoint: false
      ServiceExecution: false
  # Cognigy.AI runtime services rules
  runtime:
    enabled: true
    disabled:
      ServiceAI: false
      ServiceAppSessionManager: false
      ServiceExecution: false
      ServiceFunctionExecution: false
      ServiceHttp: false
      ServiceNlpMatcher: false
      ServicePlaybookExecution: false
      ServiceSessionStateManager: false