{
 "title": "KubeRay / Serve Deployment Dashboard",
 "tags": [ "rayVersion:2.41.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "Application",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{cluster=\"$cluster\"}, application)"
    }
   },
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{cluster=\"$cluster\", application=~\"$Application\",}, deployment)"
    }
   },
   {
    "name": "Replica",
    "query": {
     "query": "label_values(ray_serve_deployment_replica_healthy{cluster=\"$cluster\", application=~\"$Application\",deployment=~\"$Deployment\",}, replica)"
    }
   },
   {
    "name": "Route",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{cluster=\"$cluster\", deployment=~\"$Deployment\",}, route)"
    }
   },
   {
    "name": "Cluster",
    "label": "Ray Cluster",
    "query": {
     "query": "label_values(ray_node_network_receive_speed{cluster=\"$cluster\"}, ray_io_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas per deployment",
   "type": "timeseries",
   "description": "Number of replicas per deployment. Ignores \"Route\" variable.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "replicas" } },
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "QPS per replica",
   "type": "timeseries",
   "description": "QPS for each replica.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter_total{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Error QPS per replica",
   "type": "timeseries",
   "description": "Error QPS for each replica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter_total{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P50 latency per replica",
   "type": "timeseries",
   "description": "P50 latency per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per replica",
   "type": "timeseries",
   "description": "P90 latency per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per replica",
   "type": "timeseries",
   "description": "P99 latency per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",route!~\"/-/.*\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "timeseries",
   "description": "Number of requests queued per deployment. Ignores \"Replica\" and \"Route\" variable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}) by (application, deployment)",
     "legendFormat": "{{application, deployment}}"
    }
   ]
  },
  {
   "title": "Running requests per replica",
   "type": "timeseries",
   "description": "Current running requests for each replica.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum(ray_serve_replica_processing_queries{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed models per replica",
   "type": "timeseries",
   "description": "The number of multiplexed models for each replica.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "models" } },
   "targets": [
    {
     "expr": "sum(ray_serve_num_multiplexed_models{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model loads per replica",
   "type": "timeseries",
   "description": "The number of times of multiplexed models loaded for each replica.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "targets": [
    {
     "expr": "sum(ray_serve_multiplexed_models_load_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model unloads per replica",
   "type": "timeseries",
   "description": "The number of times of multiplexed models unloaded for each replica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "targets": [
    {
     "expr": "sum(ray_serve_multiplexed_models_unload_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}) by (application, deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P99 latency of multiplexed model loads per replica",
   "type": "timeseries",
   "description": "P99 latency of mutliplexed model load per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_multiplexed_model_load_latency_ms_bucket{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P99 latency of multiplexed model unloads per replica",
   "type": "timeseries",
   "description": "P99 latency of mutliplexed model unload per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_multiplexed_model_unload_latency_ms_bucket{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])) by (application, deployment, replica, le))",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Multiplexed model ids per replica",
   "type": "timeseries",
   "description": "The ids of multiplexed models for each replica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "model" } },
   "targets": [
    {
     "expr": "ray_serve_registered_multiplexed_model_id{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}",
     "legendFormat": "{{replica}}:{{model_id}}"
    }
   ]
  },
  {
   "title": "Multiplexed model cache hit rate",
   "type": "timeseries",
   "description": "The cache hit rate of multiplexed models for the deployment.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(ray_serve_multiplexed_models_load_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m]))/sum(rate(ray_serve_multiplexed_get_model_requests_counter_total{application=~\"$Application\",deployment=~\"$Deployment\",replica=~\"$Replica\",ray_io_cluster=~\"$Cluster\",cluster=\"$cluster\"}[5m])))",
     "legendFormat": "{{replica}}"
    }
   ]
  }
 ]
}