---
{{- if .Values.monitors.weaviate.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-services-weaviate
  labels:
    {{- include "cognigy-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: weaviate
  namespaceSelector:
    matchNames:
      - "{{ .Values.monitors.weaviate.namespace }}"
  podMetricsEndpoints:
    - path: /metrics
      targetPort: 2112
{{- end }}