{{- if .Values.monitors.sealedSecrets.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-sealed-secrets-controller-servicemonitor
  labels:
    {{- include "cognigy-monitors.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: sealed-secrets-controller
      app.kubernetes.io/name: sealed-secrets
  namespaceSelector:
    matchNames:
      - "{{ .Values.monitors.sealedSecrets.namespace }}"
  endpoints:
    - honorLabels: true
      port: metrics
{{- end -}}
