name: $(why)_helm_release_$(SourceBranchName)_$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
#    exclude:
#      - "*"
    include:
      - "main" ## TEMP REMOVE LATER
  tags:
    include:
      - "*"

resources:
  repositories:
    - repository: self

    - repository: GitHub
      type: github
      endpoint: github.com_mayrbenjamin92
      name: Cognigy/cognigy-monitoring-helm-chart
      ref: main

variables:
  azureContainerRegistry: "Azure Container Registry Prod"
  chartPath: "cognigy-monitoring"
  chartGithubPath: "cognigy-monitoring-helm-chart"
  AzureDevOpsRepo: "cognigy-monitoring-stack"
  chartName: "cognigy-monitoring"
  ACRName: "cognigy.azurecr.io"
  ACRPath: "helm"
  ${{ if eq(variables['Build.Reason'], 'Manual') }}:
    why: Manual
  ${{ else }}:
    why: CD

pool:
  vmImage: ubuntu-20.04


stages:
  - stage: helmChartRelease
    displayName: Create a new release tag and Helm Chart release
    #condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/') ## TEMP REENABLE LATER
    jobs:
      - job: createOciRelease
        displayName: Publish Helm Chart OCI Fragment
        steps:
          - task: HelmInstaller@0
            displayName: Install Helm 3.8.2
            inputs:
              helmVersion: 3.8.2
              checkLatestHelmVersion: false

          - task: Docker@2
            displayName: Login into container registry
            inputs:
              command: 'login'
              containerRegistry: $(azureContainerRegistry)

          - bash: |
              helm version
              helmChartVersion="$(yq e '.version' $(chartPath)/Chart.yaml)"
              echo "Helm Chart" $(chartName) "version:" $helmChartVersion
              helm package --dependency-update $(chartPath)
              helm push ./$(chartName)-$helmChartVersion.tgz oci://$(ACRName)/$(ACRPath)


      - job: createGithubRelease
        displayName: Publish Helm Chart Github repo
        steps:
          - task: HelmInstaller@0
            displayName: Install Helm 3.8.2
            inputs:
              helmVersion: 3.8.2
              checkLatestHelmVersion: false

          - checkout: self
            persistCredentials: "true"
            clean: "true"
            displayName: Checkout Helm Chart Source Repo

          - checkout: GitHub
            persistCredentials: "true"
            clean: "true"
            displayName: Checkout Helm Chart Target Repo

          - script: |
              git config --global user.email "azure-pipeline@cognigy.com"
              git config --global user.name "Azure Pipelines Bot"
              
              ls -lisa
              
              cd $(chartGithubPath)
              git remote -v
              rm -fr ./*
              cd ..

              cd $(AzureDevOpsRepo)
              pwd
              helmChartVersion="$(yq e '.version' $(chartPath)/Chart.yaml)"
              echo "Helm Chart version is $helmChartVersion"

              rm -fr .git
              rm -fr CHANGELOG
              cp -r ./ ../$(chartGithubPath)

              cd ../$(chartGithubPath)
              git remote -v
              git checkout main
              git add -A
              git commit -m "Adding files for Helm Chart $helmChartVersion"
              git tag v$helmChartVersion

              git push origin main
              git push origin tags/v$helmChartVersion