apiVersion: v1
appVersion: 0.20.9
description: A Prometheus exporter for MongoDB metrics
home: https://github.com/percona/mongodb_exporter
keywords:
- exporter
- metrics
- mongodb
- prometheus
maintainers:
- email: ssheehy@firescope.com
  name: steven-sheehy
name: prometheus-mongodb-exporter
sources:
- https://github.com/percona/mongodb_exporter
version: 2.8.1
