{
 "title": "Velero Stats",
 "description": "Stats for Velero backups",
 "tags": [ "velero" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(velero_backup_attempt_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Backup",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_active_total{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(velero_backup_success_total[24h])) / sum(rate(velero_backup_attempt_total[24h]))"
    }
   ]
  },
  {
   "title": "Backup per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total[24h]))",
     "legendFormat": "Backup success"
    },
    {
     "expr": "sum(increase(velero_backup_failure_total{service=~\"$service\"}[24h]))",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "sum(increase(velero_backup_partial_failure_total{service=~\"$service\"}[24h]))",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_success_total{service=~\"$service\"}[1h]))",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_failure_total{service=~\"$service\"}[1h]))",
     "legendFormat": "Backup deletion failure"
    }
   ]
  },
  {
   "title": "Backup Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velero_backup_total", "legendFormat": "Backup Total" },
    {
     "expr": "velero_backup_active_total{schedule=~\"$schedule\"}",
     "legendFormat": "Backup {{schedule}}"
    }
   ]
  },
  {
   "title": "Backup Failure Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velero_backup_failure_total", "legendFormat": "Backup Total" }
   ]
  },
  {
   "title": "Backup Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(velero_backup_duration_seconds_bucket{service=~\"$service\"}[15m])) by (le))",
     "legendFormat": "Scheduled: 0.99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(velero_backup_duration_seconds_bucket{service!~\".*\"}[15m])) by (le))",
     "legendFormat": "Non Scheduled: 0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(velero_backup_duration_seconds_bucket{service=~\"$service\"}[15m])) by (le))",
     "legendFormat": "Scheduled: 0.95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(velero_backup_duration_seconds_bucket{service!~\".*\"}[15m])) by (le))",
     "legendFormat": "Non Scheduled: 0.95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(velero_backup_duration_seconds_bucket{service=~\"$service\"}[15m])) by (le))",
     "legendFormat": "Scheduled: 0.50"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(velero_backup_duration_seconds_bucket{service!~\".*\"}[15m])) by (le))",
     "legendFormat": "Non Scheduled: 0.50"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(velero_backup_tarball_size_bytes{service=~\"$service\"}[15m])",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "avg_over_time(velero_backup_tarball_size_bytes{service!~\".*\"}[15m])",
     "legendFormat": "Non Scheduled"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{service!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Restore",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(velero_restore_attempt_total[$__interval])) / sum(rate(velero_restore_success_total[$__interval]))"
      }
     ]
    },
    {
     "title": "Restore Success",
     "type": "graph",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(velero_restore_success_total{service!~\".*\"}[15m])) / sum(rate(velero_restore_attempt_total{service!~\".*\"}[15m]))",
       "legendFormat": "Backup success rate"
      },
      {
       "expr": "sum(rate(velero_restore_success_total{service=~\"$service\"}[15m])) / sum(rate(velero_restore_attempt_total{service=~\"$service\"}[15m]))",
       "legendFormat": "Backup success rate {{schedule}}"
      }
     ]
    },
    {
     "title": "Total Restore Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(velero_restore_total[15m]) ",
       "legendFormat": "Restore Total"
      },
      {
       "expr": "avg_over_time(velero_restore_success_total{schedule=~\"$schedule\"}[15m])",
       "legendFormat": "Restore Success Total {{schedule}}"
      },
      {
       "expr": "avg_over_time(velero_restore_success_total{schedule!~\".*\"}[15m])",
       "legendFormat": "Restore Success Total"
      },
      {
       "expr": "avg_over_time(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[15m])",
       "legendFormat": " Restore Partial Failure Total {{schedule}}"
      },
      {
       "expr": "avg_over_time(velero_restore_partial_failure_total{schedule!~\".*\"}[15m])",
       "legendFormat": "Restore Partial Failure Total"
      },
      {
       "expr": "avg_over_time(velero_restore_failed_total{schedule=~\"$schedule\"}[15m])",
       "legendFormat": "Restore Failure Total {{schedule}}"
      },
      {
       "expr": "avg_over_time(velero_restore_failed_total{schedule!~\".*\"}[15m])",
       "legendFormat": "Restore Failure Total"
      },
      {
       "expr": "avg_over_time(velero_restore_validation_failed_total{schedule=~\"$schedule\"}[15m])",
       "legendFormat": "Restore Validation Failed {{schedule}}"
      },
      {
       "expr": "avg_over_time(velero_restore_validation_failed_total{schedule!~\".*\"}[15m])",
       "legendFormat": "Restore Validation Failed"
      }
     ]
    }
   ]
  }
 ]
}