{
 "title": "Agents Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "organisationName",
    "label": "Organisation",
    "query": {
     "query": "label_values(cognigy_ai_flow_execution_processing_time_count, organisationName)"
    }
   },
   {
    "name": "projectId",
    "label": "Project",
    "query": {
     "query": "cognigy_ai_flow_execution_processing_time_count{organisationName=~\"$organisationName\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Overview\n\nThis dashboard displays key metrics for how Virtual Agents are performing across different projects.\n\nIt is possible to filter based on organisation and project. The tables here show a mapping between organisationName -> organisationId and projectName -> projectId.\n\n# Compatibility\nThis dashboard requires version 4.47.0 of Cognigy.AI to work."
   }
  },
  {
   "title": "Projects",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(cognigy_ai_flow_execution_processing_time_count{organisationName=~\"$organisationName\"}) by (projectId, projectName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Organisations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(cognigy_ai_flow_execution_processing_time_count{organisationName=~\"$organisationName\"}) by (organisationName, organisationId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages Processed per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_endpoint_raw_messages_count{projectId=~\"$projectId\"}[1m])) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Messages Processed Total",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_endpoint_raw_messages_count{projectId=~\"$projectId\"}) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Messages Processed per Interval",
   "type": "piechart",
   "description": "Messages Processed within the specified interval per Project",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_endpoint_raw_messages_count{projectId=~\"$projectId\"}[$__interval])) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Message Processing Time (90th Percentile)",
   "type": "timeseries",
   "description": "90th Quantile of Message Processing Time per Project",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_endpoint_raw_messages_response_time_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Message Processing Time",
   "type": "heatmap",
   "description": "Heatmap of Message Processing Time per Project",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cognigy_endpoint_raw_messages_response_time_bucket{projectId=~\"$projectId\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Knowledge AI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 42 },
   "options": {
    "content": "# Knowledge AI\n\nThe Knowledge AI feature was introduced as part of Cognigy.AI v4.57.0 as part of a private-beta. The feature might not be enabled on your Cognigy.AI system."
   }
  },
  {
   "title": "Successful Search Requests (total)",
   "type": "stat",
   "description": "Shows the total number of search requests since the last restart.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(search_orchestrator_successful_search_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Latency (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(increase(search_orchestrator_search_latency_histogram_seconds_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 42 },
   "targets": [
    {
     "expr": "sum by(le) (increase(search_orchestrator_search_latency_histogram_seconds_bucket{projectId=~\"$projectId\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Flow Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Flow Execution Time (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_ai_message_processing_time_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Flow Execution Errors",
   "type": "timeseries",
   "description": "Flow Execution Errors per Minute",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum (increase(cognigy_ai_messages_error_total{projectId=~\"$projectId\"}[1m])) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  { "title": "NLP V1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Score Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_score_rpc_counter_total{projectId=~\"$projectId\"}[1m])) by (projectId, organisationId, container)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Train Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_train_rpc_counter_total{projectId=~\"$projectId\"}[1m])) by (projectId, organisationId, container)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Score RPC latency (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId, container))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Train RPC latency (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId, container))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  { "title": "NLP V2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Classifier Score Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_score_rpc_counter_total{projectId=~\"$projectId\"}[1m])) by (projectId, organisationId, container)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Classifier Train Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_train_rpc_counter_total{projectId=~\"$projectId\"}[1m])) by (projectId, organisationId, container)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Classifier Score RPC latency (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_score_rpc_latency_histogram_milliseconds_bucket{projectId=~\"$projectId\"}[1m])) by (le, container, organisationId, projectId))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Classifier Train RPC latency (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_train_rpc_latency_histogram_seconds_bucket{projectId=~\"$projectId\"}[1m])) by (le, container, organisationId, projectId))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}} | Language: {{container}}"
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint Transformer Processing Time (90th Percentile)",
   "type": "timeseries",
   "description": "Endpoint Transformer Processing Time (90th Percentile) per Project",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_endpoint_transformer_execution_time_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Endpoint Transformer Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_endpoint_transformer_error_count{projectId=~\"$projectId\"}[1m])) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Handover",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Handovers Started / Minute",
   "type": "timeseries",
   "description": "Handovers Started events per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum (increase(cognigy_ai_handover_amount{projectId=~\"$projectId\"}[1m])) by (organisationId, projectId)"
    }
   ]
  },
  {
   "title": "Handover Errors / Minute",
   "type": "timeseries",
   "description": "Handover Errors per Minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum (increase(cognigy_ai_handover_error_amount{projectId=~\"$projectId\"}[1m])) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Extensions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Extensions Used Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (organisationId, projectId) (cognigy_execution_extension_processing_time_count{projectId=~\"$projectId\"})",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Extensions Used per Interval",
   "type": "piechart",
   "description": "Extensions Usage per specified Interval",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (organisationId, projectId) (increase(cognigy_execution_extension_processing_time_count{projectId=~\"$projectId\"}[$__interval]))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Extensions Execution Time (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_execution_extension_processing_time_bucket{projectId=~\"$projectId\"}[1m])) by (le, organisationId, projectId))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Extensions Executions / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (organisationId, projectId) (increase(cognigy_execution_extension_processing_time_count{projectId=~\"$projectId\"}[1m]))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Functions Schedules / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum by (organisationId, projectId) (increase(cognigy_function_scheduler_scheduled_functions_count{}[1m]))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Functions Executions / Minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "sum by (organisationId, projectId) (increase(cognigy_function_execution_processing_time_count{}[1m]))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Functions Scheduling Conflicts / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_function_scheduler_scheduling_conflict_count{}[1m])) by (organisationId, projectId)"
    }
   ]
  },
  {
   "title": "Functions Usage Total",
   "type": "piechart",
   "description": "How often are extensions being used per Project.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_function_execution_processing_time_count{projectId=~\"$projectId\"}) by (organisationId, projectId)",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  },
  {
   "title": "Functions Usage per Interval",
   "type": "piechart",
   "description": "Functions Usage per Interval per Project.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (organisationId, projectId) (increase(cognigy_function_execution_processing_time_count{projectId=~\"$projectId\"}[$__interval]))",
     "legendFormat": "Org: {{organisationId}} | Project: {{projectId}}"
    }
   ]
  }
 ]
}