{
 "title": "Cognigy.AI Overview Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod restarts (last 12h)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"default\"} - kube_pod_container_status_restarts_total{namespace=\"default\"} offset 12h)"
    }
   ]
  },
  {
   "title": "K8s Cluster CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((\n  instance:node_cpu_utilisation:rate5m{job=\"node-exporter\"}\n  *\n  instance:node_num_cpu:sum{job=\"node-exporter\"}\n) != 0 )\n/ scalar(sum(instance:node_num_cpu:sum{job=\"node-exporter\"}))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RabbitMQ Unacked Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "Redis Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total[5m])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Available pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"default\"}) / sum(kube_deployment_status_replicas{namespace=\"default\"}) * 100"
    }
   ]
  },
  {
   "title": "K8s Cluster Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\"}\n  / scalar(count(instance:node_memory_utilisation:ratio{job=\"node-exporter\"}))\n) != 0\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MongoDB Replica Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_member_health)",
     "legendFormat": "member health"
    }
   ]
  },
  {
   "title": "Redis Total Time Spent by Command / sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Messages per Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_endpoint_raw_messages_count[1h]))",
     "legendFormat": "messages"
    }
   ]
  },
  {
   "title": "Message processing time",
   "type": "timeseries",
   "description": "How long did Cognigy.AI need in order to process the input entirely?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_endpoint_raw_messages_response_time_bucket[5m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_endpoint_raw_messages_response_time_bucket[5m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_endpoint_raw_messages_response_time_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_endpoint_raw_messages_response_time_bucket[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "NLP Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_score_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_score_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_score_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_score_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Requests per backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{namespace=\"default\"}[1m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "NLP Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_train_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_train_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_train_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_train_rpc_latency_histogram_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Non-200 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{namespace=\"default\",code!~\"2..\"}[5m])) by (method, code)",
     "legendFormat": "{{ method }} : {{ code }}"
    }
   ]
  }
 ]
}