{
 "title": "AI / Conversation Counter & Billing",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Local Conversation Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "# Explanation\n\nThe graph on the right side shows metrics\nfor the local conversation counter within\nevery Cognigy.AI installation."
   }
  },
  {
   "title": "Local Conversation Counter Errors",
   "type": "timeseries",
   "description": "Show the number of errors storing the conversation counter locally within the Cognigy.AI system itself.",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_security_conversation_counter_errors_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Conversation Counter Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_security_conversation_counter_message_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Central Billing Server - Submission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Central Billing Reporting - Success / Failure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_security_billing_report_processing_success_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Success Count"
    },
    {
     "expr": "sum(increase(cognigy_security_billing_report_processing_failure_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Failure Count"
    },
    {
     "expr": "sum(increase(cognigy_security_billing_report_storing_failure_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "SQL Failure Count"
    }
   ]
  }
 ]
}