{
 "title": "GenerativeAi",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rephrase Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rephrase Generation #Executions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_ai_generative_ai_rephrase_output_requests_count) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rephrase Generation #TimeOuts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_ai_generative_ai_rephrase_output_timeouts_count) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rephrase Generation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(cognigy_ai_generative_ai_rephrase_output_requests_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "cognigy_ai_generative_ai_rephrase_output_requests_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flow Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Flow Generation #Executions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_counter_flow_generation) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Generation #failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_counter_flow_generation_failure) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Generation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(cognigy_resources_counter_flow_generation{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Generation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(cognigy_resources_counter_flow_generation{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lexicon Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Lexicon Generation #Executions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_lexicon_entries_generation_duration_ms_count) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lexicon Generation #failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_counter_lexicon_entries_generation_failure) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lexicon Generation runs x bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_lexicon_entries_generation_duration_ms_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Lexicon Generation parsing output #Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_counter_lexicon_entries_generation_parsing_output_error) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lexicon Generation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(cognigy_resources_counter_lexicon_entries_generation{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lexicon Generation Histogram Sum",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "cognigy_resources_lexicon_entries_generation_duration_ms_sum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Intent Sentences Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Intent Sentences Generation #Executions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_intent_sentence_generation_duration_ms_count) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intent Sentences #failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_counter_intent_sentence_generation_failure) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intent Sentences Generation runs x bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_intent_sentence_generation_duration_ms_bucket) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Intent Sentences Parsing Output #Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_resources_counter_intent_sentence_generation_parsing_output_error) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intent Sentence Generation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "rate(cognigy_resources_counter_intent_sentence_generation{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}