{
 "title": "AI / LLM Providers - OAuth2 Token Management",
 "tags": [
  "oauth2",
  "llm-providers",
  "authentication"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "provider",
    "query": "label_values(oauth2_token_requests_total, provider)"
   },
   {
    "name": "client_id",
    "query": "label_values(oauth2_token_requests_total{provider=~\"$provider\"}, client_id)"
   }
  ]
 },
 "panels": [
  { "title": "Token Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Token Usage by Cluster",
   "type": "piechart",
   "description": "Token Usage is defined by the sum of all\n- successful, failed, and retried token requests\n- cache hits and misses",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  oauth2_token_requests_total{cluster=~\"$cluster\"}\n  or oauth2_token_retry_attempts_total{cluster=~\"$cluster\"}\n  or oauth2_token_cache_hits_total{cluster=~\"$cluster\"}\n  or oauth2_token_cache_misses_total{cluster=~\"$cluster\"}\n) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Token Usage by Provider",
   "type": "piechart",
   "description": "Token Usage is defined by the sum of all \n- successful, failed, and retried token requests\n- cache hits and misses",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\"}\n  or oauth2_token_retry_attempts_total{cluster=~\"$cluster\",provider=~\"$provider\"}\n  or oauth2_token_cache_hits_total{cluster=~\"$cluster\",provider=~\"$provider\"}\n  or oauth2_token_cache_misses_total{cluster=~\"$cluster\",provider=~\"$provider\"}\n) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Token Usage by Client",
   "type": "piechart",
   "description": "Token Usage is defined by the sum of all\n- successful, failed, and retried token requests\n- cache hits and misses",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}\n  or oauth2_token_retry_attempts_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}\n  or oauth2_token_cache_hits_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}\n  or oauth2_token_cache_misses_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}\n) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "Token Request Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Token Request Success Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\",status=\"success\"}[$__range])) / sum(increase(oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Successful Token Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\",status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Failed Token Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\",status=\"failure\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Token Request Retry Attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_retry_attempts_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Token Request Timeouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_request_timeout_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average Token Request Latency (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(oauth2_token_request_duration_seconds_sum{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__rate_interval])) by (cluster, provider, client_id, status) / sum(rate(oauth2_token_request_duration_seconds_count{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__rate_interval])) by (cluster, provider, client_id, status) * 1000",
     "legendFormat": "{{cluster}} - {{provider}} - {{client_id}} ({{status}})"
    }
   ]
  },
  {
   "title": "Successful Token Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\",status=\"success\"}[1m])) by (cluster, provider)",
     "legendFormat": "{{cluster}} - {{provider}}"
    }
   ]
  },
  {
   "title": "Token Request Retry Attempts per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_retry_attempts_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[1m])) by (cluster, provider, retry_attempt)",
     "legendFormat": "{{cluster}} - {{provider}}"
    }
   ]
  },
  {
   "title": "Token Request Timeouts per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_request_timeout_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[1m])) by (cluster, provider)",
     "legendFormat": "{{cluster}} - {{provider}}"
    }
   ]
  },
  {
   "title": "Failed Token Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_requests_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\",status=\"failure\"}[1m])) by (cluster, provider)",
     "legendFormat": "{{cluster}} - {{provider}}"
    }
   ]
  },
  { "title": "Cache Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Cache Hit Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_cache_hits_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range])) / (sum(increase(oauth2_token_cache_hits_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range])) + sum(increase(oauth2_token_cache_misses_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "Total Cache Hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_cache_hits_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Hits per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_cache_hits_total{cluster=~\"$cluster\",provider=~\"$provider\"}[1m])) by (cluster, provider)",
     "legendFormat": "{{cluster}} - {{provider}}"
    }
   ]
  },
  {
   "title": "Total Cache Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_cache_misses_total{cluster=~\"$cluster\",provider=~\"$provider\",client_id=~\"$client_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Cache Misses per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oauth2_token_cache_misses_total{cluster=~\"$cluster\",provider=~\"$provider\"}[1m])) by (cluster, provider)",
     "legendFormat": "{{cluster}} - {{provider}}"
    }
   ]
  }
 ]
}