{
 "title": "NLP-v2 Shadow Mode Dashboard",
 "description": "Shows statistics of the NLP-v2 Shadow Mode",
 "time": { "from": "2022-12-09T15:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "service-nlp-classifier-score-en,service-nlp-classifier-score-de,service-nlp-classifier-score-xx,service-nlp-classifier-score-ge,service-nlp-classifier-score-ja,service-nlp-classifier-score-ko"
   }
  ]
 },
 "panels": [
  {
   "title": "NLP-v2 Stack Similarity Metrics for $deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "deployment",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Number of Score Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "% total times when intent was different",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(increase(cognigy_nlp_classifier_intent_equality_total{container=\"$deployment\"}[$__range])) / sum(increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "# total times when intent was different",
   "type": "stat",
   "description": "The total number of differences that occurred in intent predictions within NLP-v1 and NLP-v2.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ( increase(cognigy_nlp_classifier_intent_equality_total{container=\"$deployment\"}[$__range]))"
    }
   ]
  },
  {
   "title": "% total times when score was different",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (((sum(increase(cognigy_nlp_classifier_score_similarity_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) + (sum(increase(cognigy_nlp_classifier_only_v1_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) + (sum(increase(cognigy_nlp_classifier_only_v2_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0))) / sum(increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range])))"
    }
   ]
  },
  {
   "title": "# total times when score was different",
   "type": "stat",
   "description": "This includes:\n- Times when score was different\n- Times when only NLP-v1 scored\n- Times when only NLP-v2 scored ",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(cognigy_nlp_classifier_score_similarity_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) + (sum(increase(cognigy_nlp_classifier_only_v1_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) + (sum(increase(cognigy_nlp_classifier_only_v2_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "% times when embedding was different",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum ( increase(cognigy_nlp_classifier_embedding_similarity_total{container=\"$deployment\"}[$__range])) / sum ( increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "# times when embedding was different",
   "type": "stat",
   "description": "The total number of differences that occurred in the embeddings of input sentences within NLP-v1 and NLP-v2. NLP-v1 embeds the input sentences directly within the service, whereas NLP-v2 embeds them in a dedicated embedding service.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ( increase(cognigy_nlp_classifier_embedding_similarity_total{container=\"$deployment\"}[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "% times when score was different",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ((sum(increase(cognigy_nlp_classifier_score_similarity_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) / sum(increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range])))"
    }
   ]
  },
  {
   "title": "# times when score was different",
   "type": "stat",
   "description": "The total number of differences that occurred in intent prediction probabilities within NLP-v1 and NLP-v2.",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_score_similarity_total{container=\"$deployment\"}[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "% times when slots were different",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(increase(cognigy_nlp_classifier_slot_name_differences_total{container=\"$deployment\"}[$__range])) / sum (increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range]))) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "# times when slots were different",
   "type": "stat",
   "description": "The total number of differences that occurred in detected slots within NLP-v1 and NLP-v2.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ( increase(cognigy_nlp_classifier_slot_name_differences_total{container=\"$deployment\"}[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "% times when only NLP-v1 scored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ((sum(increase(cognigy_nlp_classifier_only_v1_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) / sum(increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range])))"
    }
   ]
  },
  {
   "title": "# times when only NLP-v1 scored",
   "type": "stat",
   "description": "Number of times where the NLP-v1 stack scored an intent, but the NLP-v2 stack did not",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_only_v1_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "% times when only NLP-v2 scored",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ((sum(increase(cognigy_nlp_classifier_only_v2_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0)) / sum(increase(cognigy_nlp_classifier_score_rpc_shadow_mode_total{container=\"$deployment\"}[$__range])))"
    }
   ]
  },
  {
   "title": "# times when only NLP-v2 scored",
   "type": "stat",
   "description": "Number of times where the NLP-v2 stack scored an intent, but the NLP-v1 stack did not",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_only_v2_scored_total{container=\"$deployment\"}[$__range])) OR on() vector(0)"
    }
   ]
  }
 ]
}