{
 "title": "AI / Node Config Fallback",
 "tags": [
  "cognigy",
  "cognigy.ai"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "indexChartNodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "indexChartNodes calls",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_index_chart_nodes_latency_count{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval]))",
     "legendFormat": "Node Config Fallback enabled"
    },
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_index_chart_nodes_latency_count{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval]))",
     "legendFormat": "Node Config Fallback disabled"
    }
   ]
  },
  {
   "title": "indexChartNodes calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_index_chart_nodes_latency_count{cluster=\"$cluster\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "indexChartNodes adoption rate",
   "type": "gauge",
   "description": "quota of indexChartNodes RPC calls with \"Node Config Fallback\" enabled",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_index_chart_nodes_latency_count{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[1h])) / sum(increase(cognigy_resources_node_config_fallback_index_chart_nodes_latency_count{cluster=\"$cluster\"}[1h]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "indexChartNodes NCF errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"indexChartNodes\",result!=\"success\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "indexChartNodes NCF success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"indexChartNodes\",result=\"success\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"indexChartNodes\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "indexChartNodes in-process latency using NCF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "indexChartNodes in-process latency without NCF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "indexChartNodes in-process latency using NCF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "indexChartNodes in-process latency without NCF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "indexChartNodes absolute latency offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "indexChartNodes relative latency offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_index_chart_nodes_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "readChartNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "readChartNode calls",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_read_chart_node_latency_count{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval]))",
     "legendFormat": "Node Config Fallback enabled"
    },
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_read_chart_node_latency_count{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval]))",
     "legendFormat": "Node Config Fallback disabled"
    }
   ]
  },
  {
   "title": "readChartNode calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_read_chart_node_latency_count{cluster=\"$cluster\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "readChartNode adoption rate",
   "type": "gauge",
   "description": "quota of readChartNode RPC calls with \"Node Config Fallback\" enabled",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_read_chart_node_latency_count{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_read_chart_node_latency_count{cluster=\"$cluster\",}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "readChartNode NCF errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"readChartNode\",result!=\"success\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "readChartNode NCF success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"readChartNode\",result=\"success\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"readChartNode\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "readChartNode in-process latency using NCF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "readChartNode in-process latency without NCF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "readChartNode in-process latency using NCF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "readChartNode in-process latency without NCF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "readChartNode absolute latency offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) - histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "readChartNode relative latency offset",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.80, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.90, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.95, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"true\"}[$__range])) by (le)) / histogram_quantile(0.99, sum(rate(cognigy_resources_node_config_fallback_read_chart_node_latency_bucket{cluster=\"$cluster\",nodeConfigFallbackEnabled=\"false\"}[$__range])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "createChartNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "createChartNode NCF calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"createChartNode\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "createChartNode NCF errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"createChartNode\",result!=\"success\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "createChartNode NCF success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"createChartNode\",result=\"success\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"createChartNode\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  { "title": "updateChartNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "updateChartNode NCF calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"updateChartNode\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "updateChartNode NCF errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"updateChartNode\",result!=\"success\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "updateChartNode NCF success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"updateChartNode\",result=\"success\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_method_execution_count{cluster=\"$cluster\",method=\"updateChartNode\"}[$__range]))",
     "legendFormat": "Node Config Fallback enabled"
    }
   ]
  },
  {
   "title": "Node Config Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Node Configs",
     "type": "timeseries",
     "description": "Amount of processed Node Configs per timeframe, as total and ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\",nodeConfigFallbackApplied=\"valid\"}[$__rate_interval]))",
       "legendFormat": "valid"
      },
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\",nodeConfigFallbackApplied=\"converted\"}[$__rate_interval]))",
       "legendFormat": "adjusted"
      }
     ]
    },
    {
     "title": "Node Configs processed",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\",nodeConfigFallbackApplied=\"valid\"}[$__range]))",
       "legendFormat": "valid"
      },
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\",nodeConfigFallbackApplied=\"converted\"}[$__range]))",
       "legendFormat": "adjusted"
      },
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_convert_node_execution_count{cluster=\"$cluster\",result=\"error\"}[$__range]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Ratio of adjusted Node Configs over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\",nodeConfigFallbackApplied=\"converted\"}[1h])) / sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\"}[1h]))",
       "legendFormat": "ratio of converted node configs"
      }
     ]
    },
    {
     "title": "Node Configs adjusted during processing",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\",nodeConfigFallbackApplied=\"converted\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_processed_node_conversion_count{cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "ratio of converted node configs"
      }
     ]
    },
    {
     "title": "Node Config Conversion Success Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_resources_node_config_fallback_convert_node_execution_count{cluster=\"$cluster\",result=\"success\"}[$__range])) / sum(increase(cognigy_resources_node_config_fallback_convert_node_execution_count{cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}