{
 "title": "AI / PII feature Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All orgs - Logs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_ai_logs_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_logs_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cognigy_ai_logs_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "All orgs - Insights",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_collector_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_collector_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(cognigy_collector_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "Redacted data size - Logs",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_logs_pii_redaction_data_size_bucket{cluster=\"$cluster\", dataType=\"data\"}[$__rate_interval])) by (le))",
     "legendFormat": "Data"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_logs_pii_redaction_data_size_bucket{cluster=\"$cluster\", dataType=\"text\"}[$__rate_interval])) by (le))",
     "legendFormat": "Text"
    }
   ]
  },
  {
   "title": "Redacted data size - Insights",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_collector_pii_redaction_data_size_bucket{cluster=\"$cluster\",dataType=\"inputText\"}[$__rate_interval])) by (le))",
     "legendFormat": "inputText"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_collector_pii_redaction_data_size_bucket{cluster=\"$cluster\", dataType=\"inputData\"}[$__rate_interval])) by (le))",
     "legendFormat": "inputData"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_collector_pii_redaction_data_size_bucket{cluster=\"$cluster\", dataType=\"previousInputData\"}[$__rate_interval])) by (le))",
     "legendFormat": "previousInputData"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_collector_pii_redaction_data_size_bucket{cluster=\"$cluster\", dataType=\"previousInputText\"}[$__rate_interval])) by (le))",
     "legendFormat": "previousInputText"
    }
   ]
  },
  {
   "title": "Per Org - Logs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_logs_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (organisationId, le))",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Per Org - Insights",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_collector_pii_redaction_latency_bucket{cluster=\"$cluster\"}[$__rate_interval])) by (organisationId, le))",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Error - Logs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_ai_logs_pii_redaction_errors_total{cluster=\"$cluster\"}[$__rate_interval])) * 60",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Error - Insights",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_collector_pii_redaction_errors_total{cluster=\"$cluster\"}[$__rate_interval])) * 60",
     "legendFormat": "{{organisationId}}"
    }
   ]
  }
 ]
}