{
 "title": "RPC Execution Average Time",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average RPC Execution Time for Service-api",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-api\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-api\"}[1m])) by (queue, type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPC Execution Time for Service-resources",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-resources\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-resources\"}[1m])) by (queue, type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPC Execution Time for service-security",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-security\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-security\"}[1m])) by (queue, type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPC Execution Time for service-task-manager",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-task-manager\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-task-manager\"}[1m])) by (queue, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPC Execution Time for service-trainer",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-trainer\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-trainer\"}[1m])) by (queue, type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPC Execution Time for service-custom-modules",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-custom-modules\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-custom-modules\"}[1m])) by (queue, type)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RPC Execution Time for service-webchat",
   "type": "timeseries",
   "description": "The dashboard presents a graph that shows the average execution time over time for each queue and type combination, using different colors to represent each combination. It also displays a table which shows the total of all the calculated values for all queue and type combinations. This total represents the sum of the calculated average execution times for each queue and type combination.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_services_histogram_rpc_execution_time_count{container=\"service-webchat\"}[1m])) by (queue, type)-sum(rate(cognigy_services_histogram_rpc_execution_time_bucket{le=\"8000\",container=\"service-webchat\"}[1m])) by (queue, type)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}