{
 "title": "Service-NLP-Matcher",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rpc calls count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_matcher_rpc_calls_count{cluster=\"$cluster\", rpc_type=\"findKeyphrases\"}[1m]))",
     "legendFormat": "findKeyphrases rpc call"
    },
    {
     "expr": "sum(increase(cognigy_matcher_rpc_calls_count{cluster=\"$cluster\", rpc_type=\"initializeLexicon\"}[1m]))",
     "legendFormat": "initializeLexicon rpc call"
    },
    {
     "expr": "sum(increase(cognigy_matcher_rpc_calls_count{cluster=\"$cluster\", rpc_type=\"batchFindKeyphrases\"}[1m]))",
     "legendFormat": "batchFindKeyphrases rpc call"
    },
    {}
   ]
  },
  {
   "title": "Find Keyphrases Failures",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cognigy_matcher_findkeyphrases_error{cluster=\"$cluster\"}",
     "legendFormat": "findKeyphrases failure"
    }
   ]
  },
  {
   "title": "Initialize Lexicon Failures",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cognigy_matcher_initialize_lexicon_error{cluster=\"$cluster\"}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Garbage Collection alloc_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=\"$cluster\", container=\"service-nlp-matcher\"}[1m])",
     "legendFormat": "alloc_bytes_total"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes{cluster=\"$cluster\", container=\"service-nlp-matcher\"}[1m])",
     "legendFormat": "alloc_bytes"
    }
   ]
  },
  { "title": "Response times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Response time Find Keyphrases for 1 Lexicon (avg 5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {},
    {
     "expr": "avg_over_time(cognigy_matcher_find_keyphrases_for_single_lexicon_response_time_sum{cluster=\"$cluster\"}[5m])\n/\navg_over_time(cognigy_matcher_find_keyphrases_for_single_lexicon_response_time_count{cluster=\"$cluster\"}[5m])",
     "legendFormat": "avg response time"
    }
   ]
  },
  {
   "title": "Response time Initialize Lexicon (avg 5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {},
    {
     "expr": "avg_over_time(cognigy_matcher_initialize_lexicon_process_time_sum{cluster=\"$cluster\"}[1m])\n/\navg_over_time(cognigy_matcher_initialize_lexicon_process_time_count{cluster=\"$cluster\"}[1m])",
     "legendFormat": "avg response time"
    }
   ]
  },
  {
   "title": "Find Keyphrases for single Lex  Process Time Buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_matcher_find_keyphrases_for_single_lexicon_response_time_bucket{cluster=\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initialize Lexicon Process Time Buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_matcher_initialize_lexicon_process_time_bucket{cluster=\"$cluster\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Find keyphrases  process time bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(cognigy_matcher_find_keyphrases_for_single_lexicon_response_time_bucket{cluster=\"$cluster\"}[5m])"
    }
   ]
  },
  {
   "title": "Initialize lexicon process time bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(cognigy_matcher_initialize_lexicon_process_time_bucket{cluster=\"$cluster\"}[5m])"
    }
   ]
  },
  { "title": "-", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } }
 ]
}