{
 "title": "AI / Service Collaboration",
 "tags": [
  "cognigy",
  "cognigy.ai"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Message Count",
   "type": "timeseries",
   "description": "Tracks the count of all requests in service-collaboration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_handle_consumer_message_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Total Messages"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "description": "Number of messages that were processed by the service-collaboration microservice",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_collaboration_handle_consumer_message_error_count{cluster=\"$cluster\", container=\"service-collaboration\"}[5m]) )",
     "legendFormat": "errorCount"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kind)(rate(cognigy_collaboration_handle_consumer_message_execution_time_sum{cluster=\"$cluster\", container=\"service-collaboration\"}[5m])) / sum by (kind)(rate(cognigy_collaboration_handle_consumer_message_execution_time_count{cluster=\"$cluster\", container=\"service-collaboration\"}[5m]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Uncaught errors / Unhandled rejections",
   "type": "timeseries",
   "description": "Number of uncaught errors and unhandled rejections in service-collaboration microservice",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_collaboration_uncaught_error_total{cluster=\"$cluster\", container=\"service-collaboration\"}[5m]) )",
     "legendFormat": "uncaughtError"
    },
    {
     "expr": "sum(rate(cognigy_collaboration_unhandled_rejection_total{cluster=\"$cluster\", container=\"service-collaboration\"}[5m]) )",
     "legendFormat": "unhandledRejection"
    }
   ]
  },
  {
   "title": "CPU Usage service-collaboration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n  * on(pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=\"service-collaboration\", workload_type=\"deployment\"}\n)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Garbage collector activity service-collaboration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kind)(rate(nodejs_gc_duration_seconds_sum{cluster=\"$cluster\", container=\"service-collaboration\"}[5m])) / sum by (kind)(rate(nodejs_gc_duration_seconds_count{cluster=\"$cluster\", container=\"service-collaboration\"}[5m]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "TCP connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "HTTP TCP Socket Count",
   "type": "stat",
   "description": "The amount of concurrent TCP connections (mostly socket.io connections) handled by service-collaboration",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_collaboration_tcp_socket_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "HTTP TCP socket count per replica",
   "type": "timeseries",
   "description": "Number of open HTTP TCP connections (mostly socket.io connections) handled per service-collaboration replica",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 41 },
   "targets": [
    {
     "expr": "cognigy_collaboration_tcp_socket_count{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Socket.IO API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "Tracks the count of all requests in service-collaboration",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_index_threads_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_join_activity_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_join_cursor_tracking_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_leave_activity_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_leave_cursor_tracking_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_subscribe_to_threads_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_unsubscribe_from_threads_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_update_activity_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_update_cursor_tracking_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_create_thread_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_create_thread_message_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_delete_thread_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_delete_thread_message_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_read_thread_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_update_thread_count{cluster=\"$cluster\"}[$__rate_interval])) + sum(increase(cognigy_collaboration_update_thread_message_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Request Count per Request Type",
   "type": "timeseries",
   "description": "Tracks the call count of each request type in service-collaboration",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_index_threads_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "indexThreads"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_join_activity_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "joinActivity"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_join_cursor_tracking_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "joinCursorTracking"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_leave_activity_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "leaveActivity"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_leave_cursor_tracking_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "leaveCursorTracking"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_subscribe_to_threads_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "subscribeToThreads"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_unsubscribe_from_threads_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "unsubscribeFromThreads"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_activity_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateActivity"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_cursor_tracking_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateCursorTracking"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_create_thread_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "createThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_create_thread_message_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "createThreadMessage"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_delete_thread_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "deleteThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_delete_thread_message_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "deleteThreadMessage"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_read_thread_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "readThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_thread_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_thread_message_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateThreadMessage"
    }
   ]
  },
  {
   "title": "Request Error Count",
   "type": "timeseries",
   "description": "Tracks the count of all request errors in service-collaboration",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_leave_activity_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_leave_cursor_tracking_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_read_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_subscribe_to_threads_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_uncaught_error_total{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_unsubscribe_from_threads_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_update_activity_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_update_cursor_tracking_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_update_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_update_thread_message_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_create_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_create_thread_message_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_delete_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_delete_thread_message_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_index_threads_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_join_activity_error_count{cluster=\"$cluster\"}[$__rate_interval]) +\nincrease(cognigy_collaboration_join_cursor_tracking_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Errors per Request Type",
   "type": "timeseries",
   "description": "Tracks the error count of each request type in service-collaboration",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_index_threads_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "indexThreads"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_join_activity_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "joinActivity"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_join_cursor_tracking_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "joinCursorTracking"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_leave_activity_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "leaveActivity"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_leave_cursor_tracking_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "leaveCursorTracking"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_subscribe_to_threads_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "subscribeToThreads"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_unsubscribe_from_threads_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "unsubscribeFromThreads"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_activity_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateActivity"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_cursor_tracking_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateCursorTracking"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_create_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "createThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_create_thread_message_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "createThreadMessage"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_delete_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "deleteThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_delete_thread_message_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "deleteThreadMessage"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_read_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "readThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_thread_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateThread"
    },
    {
     "expr": "sum(increase(cognigy_collaboration_update_thread_message_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "updateThreadMessage"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "description": "Shows the duration percentile of request processing time in service-collaborations socket api",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum by (le) (\n    increase(cognigy_collaboration_create_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_index_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_subscribe_to_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_unsubscribe_from_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_create_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_read_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (\n    increase(cognigy_collaboration_create_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_index_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_subscribe_to_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_unsubscribe_from_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_create_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_read_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n    increase(cognigy_collaboration_create_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_index_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_subscribe_to_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_unsubscribe_from_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_create_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_read_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n    increase(cognigy_collaboration_create_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_index_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_join_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_leave_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_subscribe_to_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_unsubscribe_from_threads_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_activity_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_cursor_tracking_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_create_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_delete_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_read_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) +\n    increase(cognigy_collaboration_update_thread_message_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "Outgoing Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Outgoing Request Count per Request Type",
   "type": "timeseries",
   "description": "Tracks the call count of each outgoing request type in service-collaboration",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_send_system_mail_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "sendSystemMail"
    }
   ]
  },
  {
   "title": "Errors per Outgoing Request Type",
   "type": "timeseries",
   "description": "Tracks the error count of each outgoing request type in service-collaboration",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_collaboration_send_system_mail_error_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "sendSystemMail"
    }
   ]
  },
  {
   "title": "Outgoing Request Processing Time",
   "type": "timeseries",
   "description": "Shows the duration percentile of outgoing request processing time in service-collaborations socket api",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(\n    increase(cognigy_collaboration_send_system_mail_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(\n    increase(cognigy_collaboration_send_system_mail_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(\n    increase(cognigy_collaboration_send_system_mail_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval])\n) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(\n    increase(cognigy_collaboration_send_system_mail_execution_time_bucket{cluster=\"$cluster\"}[$__rate_interval]) \n) by (le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}