{
 "title": "AI / Service Collaboration Usage",
 "time": { "from": "now-30m", "to": "now-30s" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "organisation",
    "label": "Organisation",
    "query": {
     "query": "label_values(cognigy_collaboration_activity_connection_count{cluster=\"$cluster\"},organisationId)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(cognigy_collaboration_activity_connection_count{cluster=\"$cluster\", organisationId=\"$organisation\"},projectId)"
    }
   },
   {
    "name": "anchorPath",
    "label": "Anchor Path",
    "query": {
     "query": "label_values(cognigy_collaboration_activity_connection_count{cluster=\"$cluster\", organisationId=\"$organisation\", projectId=\"$project\"},anchorPath)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Synchronized Connections",
   "type": "stat",
   "description": "Amount of connections (open browser windows) which are synchronized with at least one other connection through activities",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (organisationId, projectId, anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\"}) >= 2)",
     "legendFormat": "{{anchorPath}}"
    }
   ]
  },
  {
   "title": "Synchronized Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expression": "($Synchronized / ($Solo + $Synchronized)) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Synchronized Connections across Organisations",
   "type": "timeseries",
   "description": "Number of connections (typically browser windows) that are synchronized with at least one other connection",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum by (anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\"}) >= 2)",
     "legendFormat": "{{anchorPath}}"
    }
   ]
  },
  {
   "title": "Synchronized Connections per Organisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Synchronized Connections per Organisation",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (organisationId) (sum by (organisationId, anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\",organisationId=~\"$organisation\"}) >= 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synchronized Connections per Organisation",
   "type": "timeseries",
   "description": "Number of connections (typically browser windows) that are synchronized with at least one other connection",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (organisationId) (sum by (organisationId, anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\",organisationId=~\"$organisation\",projectId=~\"$project\",anchorPath=~\"$anchorPath\"}) >= 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synchronized Connections per Project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Synchronized Connections per Project",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (projectId) (sum by (organisationId, projectId, anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\",organisationId=~\"$organisation\"}) >= 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synchronized Connections per Project",
   "type": "timeseries",
   "description": "Number of connections (typically browser windows) that are synchronized with at least one other connection",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (projectId) (sum by (projectId, anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\",organisationId=~\"$organisation\",projectId=~\"$project\",anchorPath=~\"$anchorPath\"}) >= 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synchronized Connections per Anchor Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Synchronized Connections per Anchor Path",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\",organisationId=~\"$organisation\"}) >= 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synchronized Connections per Anchor Path",
   "type": "timeseries",
   "description": "Number of connections (typically browser windows) that are synchronized with at least one other connection",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (anchorPath) (cognigy_collaboration_activity_connection_count{cluster=\"$cluster\",organisationId=~\"$organisation\",projectId=~\"$project\",anchorPath=~\"$anchorPath\"}) >= 2",
     "legendFormat": "{{anchorPath}}"
    }
   ]
  }
 ]
}