{
 "title": "Service-Function-Execution",
 "tags": [
  "cognigy",
  "cognigy.ai"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uncaught errors",
   "type": "timeseries",
   "description": "Number of uncaught errors in service-execution microservice",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum( rate(cognigy_function_execution_uncaught_error_total[5m]))"
    }
   ]
  },
  {
   "title": "Usage by Organisation",
   "type": "piechart",
   "description": "How often are extensions being used per Organisation.",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (organisationId)(cognigy_function_execution_processing_time_count)",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Usage by Project",
   "type": "piechart",
   "description": "How often are extensions being used per Project.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (projectId)(cognigy_function_execution_processing_time_count)",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Function executions / Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_function_execution_processing_time_count[1m]))"
    }
   ]
  },
  {
   "title": "Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Function execution time",
   "type": "timeseries",
   "description": "How long did Cognigy functions run",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_function_execution_processing_time_bucket[5m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_function_execution_processing_time_bucket[5m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_function_execution_processing_time_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_function_execution_processing_time_bucket[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}