{
 "title": "AI / Service NLP Embedding",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   { "name": "language", "label": "Language", "query": "en,xx,ge" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Embedding Request Count / Minute",
   "type": "timeseries",
   "description": "Number of successful and unsuccessful inference requests received by Triton",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_request_success{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container) + sum(increase(nv_inference_request_failure{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Execution Count / Minute",
   "type": "timeseries",
   "description": "Number of actual inference batch executions. One inference run through the model equals one event. One event can contain multiple inputs that are to be encoded.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_exec_count{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Inference Count / Minute",
   "type": "timeseries",
   "description": "Number of inferences performed (a batch of \"n\" is counted as \"n\" inferences, does not include cached requests)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_count{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Successful Inferences / Minute",
   "type": "timeseries",
   "description": "Number of successful inference requests received by Triton (each request is counted as 1, even if the request contains a batch)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_request_success{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Failed Inferences / Minute",
   "type": "timeseries",
   "description": "Number of failed inference requests received by Triton (each request is counted as 1, even if the request contains a batch)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(nv_inference_request_failure{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Request Time",
   "type": "timeseries",
   "description": "Cumulative end-to-end inference request handling time (includes cached requests)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_request_duration_us{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Queue Time",
   "type": "timeseries",
   "description": "Cumulative time requests spend waiting in the scheduling queue (includes cached requests)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Compute Time (Input+Infer+Output)",
   "type": "timeseries",
   "description": "Cumulative time requests spend processing inference inputs, executing the inference model, and processing inference outputs (in the framework backend, does not include cached requests)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(nv_inference_compute_infer_duration_us{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m]) + rate(nv_inference_compute_input_duration_us{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m]) + rate(nv_inference_compute_output_duration_us{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Embedding Replica Count",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$cluster\", deployment=~\"service-nlp-embedding-$language\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}) by (container, reason)",
     "legendFormat": "{{container}}  | {{reason}}"
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Embedding Cache Hit Count",
     "type": "timeseries",
     "description": "Number of response cache hits per model",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(nv_cache_num_hits_per_model{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Embedding Cache Miss Count",
     "type": "timeseries",
     "description": "Number of response cache misses per model",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(nv_cache_num_misses_per_model{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Embedding Cache Hit Lookup Time",
     "type": "timeseries",
     "description": "Cumulative time requests spend retrieving a cached response per model on cache hits (microseconds)",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(nv_cache_hit_lookup_duration_per_model{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Embedding Cache Miss Lookup Time",
     "type": "timeseries",
     "description": "Cumulative time requests spend looking up a request hash on a cache miss (microseconds)",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(nv_cache_miss_lookup_duration_per_model{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Embedding Cache Miss Insertion Time",
     "type": "timeseries",
     "description": "Cumulative time requests spend inserting responses into the cache on a cache miss (microseconds)",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(nv_cache_miss_insertion_duration_per_model{cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[1m])",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Embedding CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Embedding CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\", }[$__rate_interval]) / increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-embedding-$language\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    }
   ]
  },
  { "title": "Memory Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Embedding Memory Usage (Not Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"service-nlp-embedding-$language\", workload_type=\"$type\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-embedding-$language\"}\n) by (pod)\n"
    }
   ]
  }
 ]
}