{
 "title": "Service-API",
 "tags": [
  "cognigy",
  "cognigy.ai"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uncaught errors",
   "type": "timeseries",
   "description": "Number of uncaught errors in service-endpoint microservice",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_api_uncaught_error_total[5m]))"
    }
   ]
  },
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "TCP Socket count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_api_tcp_socket_count)"
    }
   ]
  },
  {
   "title": "TCP connections per API replica",
   "type": "timeseries",
   "description": "Number of open TCP connections per service-api replica",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 7 },
   "targets": [
    { "expr": "cognigy_api_tcp_socket_count", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}