{
 "title": "Service-NLP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Broken pipe errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_nlp_broken_pipe_counter_total[1m]))"
    }
   ]
  },
  { "title": "English NLU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Score replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-score-en\"}"
    }
   ]
  },
  {
   "title": "Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-en\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-en\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-en\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Train replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-train-en\"}"
    }
   ]
  },
  {
   "title": "Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-en\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-en\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-en\"}[1d])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "German NLU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Score replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-score-de\"}"
    }
   ]
  },
  {
   "title": "Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-de\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-de\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-de\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Train replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-train-de\"}"
    }
   ]
  },
  {
   "title": "Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-de\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-de\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-de\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "Japanese NLU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Score replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-score-de\"}"
    }
   ]
  },
  {
   "title": "Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-ja\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-ja\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-ja\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Train replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-train-ja\"}"
    }
   ]
  },
  {
   "title": "Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-ja\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-ja\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-ja\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "XX NLU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Score replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-score-xx\"}"
    }
   ]
  },
  {
   "title": "Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-xx\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-xx\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-xx\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Train replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-train-xx\"}"
    }
   ]
  },
  {
   "title": "Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-xx\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-xx\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-xx\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "Universal language NLU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Score replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-score-ge\"}"
    }
   ]
  },
  {
   "title": "Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-ge\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-ge\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_score_rpc_latency_histogram_milliseconds_bucket{container=\"service-nlp-score-ge\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Train replica count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"service-nlp-train-ge\"}"
    }
   ]
  },
  {
   "title": "Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-ge\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-ge\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_train_rpc_latency_histogram_seconds_bucket{container=\"service-nlp-train-ge\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}