{
 "title": "Service NLP Classifier",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   { "name": "language", "label": "Language", "query": "en,de,xx,ge,ja,ko" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Classifier Score Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_score_rpc_counter_total{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Classifier Train Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_train_rpc_counter_total{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Classifier Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_classifier_score_rpc_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (le, container))",
     "legendFormat": "80th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_score_rpc_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (le, container))",
     "legendFormat": "90th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_classifier_score_rpc_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (le, container))",
     "legendFormat": "99th | {{container}}"
    }
   ]
  },
  {
   "title": "Classifier Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_classifier_train_rpc_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "80th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_train_rpc_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "90th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_classifier_train_rpc_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "99th | {{container}}"
    }
   ]
  },
  {
   "title": "Classifier Score Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_score_rpc_error_counter_total{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Classifier Train Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_train_rpc_error_counter_total{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (container)",
     "legendFormat": "90th | {{container}}"
    }
   ]
  },
  {
   "title": "Classifier Score Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "cognigy_nlp_classifier_score_current_cache_size{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(cognigy_nlp_classifier_score_max_cache_size{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"})",
     "legendFormat": "Max Cache Size"
    }
   ]
  },
  {
   "title": "Classifier replica count",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$cluster\", deployment=~\"service-nlp-classifier-.*.-$language\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Classifier Score Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(python_gc_collections_total{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", container=~\"service-nlp-classifier-.*.-$language\"}) by (container, reason)",
     "legendFormat": "{{container}}  | {{reason}}"
    }
   ]
  },
  {
   "title": "Retrieve DB Model Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_classifier_score_db_load_model_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (le, container))",
     "legendFormat": "80th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_score_db_load_model_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (le, container))",
     "legendFormat": "90th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_classifier_score_db_load_model_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (le, container))",
     "legendFormat": "99th | {{container}}"
    }
   ]
  },
  {
   "title": "Cache Misses / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_classifier_score_model_cache_miss_counter_total{cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Model Size",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cognigy_nlp_classifier_score_model_file_size_in_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "cognigy_nlp_classifier_score_model_in_memory_size_in_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Embeddings - NLP Embedding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Embeddings Train latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_classifier_train_embeddings_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "80th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_train_embeddings_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "90th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_classifier_train_embeddings_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "99th | {{container}}"
    }
   ]
  },
  {
   "title": "Embeddings Train Latency per Sentence",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_classifier_train_embeddings_latency_per_sentence_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "80th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_classifier_train_embeddings_latency_per_sentence_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "90th | {{container}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_classifier_train_embeddings_latency_per_sentence_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[1m])) by (le, container))",
     "legendFormat": "99th | {{container}}"
    }
   ]
  },
  { "title": "CPU Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Classifier Score CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-score-$language\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Classifier Train CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-train-$language\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Classifier Score CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\", }[$__rate_interval]) / increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-classifier-score-$language\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Classifier Train CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\", }[$__rate_interval]) / increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-classifier-train-$language\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\",}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    }
   ]
  },
  { "title": "Memory Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Classifier Score Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-score-$language\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Classifier Train Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-train-$language\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"service-nlp-classifier-.*.-$language\", workload_type=\"$type\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-classifier-.*.-$language\"}\n) by (pod)\n"
    }
   ]
  }
 ]
}