{
 "title": "Service-Execution",
 "tags": [
  "cognigy",
  "cognigy.ai"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uncaught errors",
   "type": "timeseries",
   "description": "Number of uncaught errors in service-execution microservice",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum( rate(cognigy_execution_uncaught_error_total[5m]))"
    }
   ]
  },
  {
   "title": "Usage by Organisation",
   "type": "piechart",
   "description": "How often are extensions being used per Organisation.",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (organisationId) (cognigy_execution_extension_processing_time_count)",
     "legendFormat": "{{organisation}}"
    }
   ]
  },
  {
   "title": "Usage by Organisation per Interval",
   "type": "piechart",
   "description": "How often are extensions being used per Organisation.",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (organisationId) (increase(cognigy_execution_extension_processing_time_count[$__interval]))",
     "legendFormat": "{{organisation}}"
    }
   ]
  },
  {
   "title": "Total cache size (MB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (cognigy_size_of_cached_extension_dir_sum)"
    }
   ]
  },
  {
   "title": "99th percentile execution time (per 5m)",
   "type": "stat",
   "description": "99th percentile of extension execution time",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_execution_extension_processing_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Extensions Executions / Minute",
   "type": "timeseries",
   "description": "Extension Executions Rate",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_execution_extension_processing_time_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extensions Executions Time",
   "type": "timeseries",
   "description": "Represens extension execution time interval in a flow node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_execution_extension_processing_time_bucket[1m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_execution_extension_processing_time_bucket[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_execution_extension_processing_time_bucket[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_execution_extension_processing_time_bucket[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Extension cache refills",
   "type": "stat",
   "description": "How often we have copied extensions to the local file-system cache",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(cognigy_cached_extension_copied[5m]))"
    }
   ]
  },
  {
   "title": "Cache size (MB)",
   "type": "piechart",
   "description": "Size of local file-system based cache for extensions",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cognigy_size_of_cached_extension_dir_sum",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cached extensions (per replica)",
   "type": "piechart",
   "description": "How often did the system cache an Extension in the locale file system?",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cognigy_cached_extension_copied",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}