{
 "title": "Service NLP Orchestrator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Orchestrator Score Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_orchestrator_score_rpc_counter_total{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Orchestrator Train Events/min Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_orchestrator_train_rpc_counter_total{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Orchestrator Score RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_score_rpc_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_score_rpc_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_score_rpc_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Orchestrator Train RPC latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_train_rpc_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_train_rpc_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_train_rpc_latency_histogram_seconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Orchestrator Score Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(python_gc_collections_total{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Orchestrator Train Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "sum(increase(cognigy_nlp_orchestrator_train_rpc_error_counter_total{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (container)",
     "legendFormat": "90th | {{container}}"
    }
   ]
  },
  {
   "title": "Orchestrator replica count",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=\"$cluster\", deployment=~\"service-nlp-orchestrator\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Orchestrator Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}) by (container, reason)",
     "legendFormat": "{{container}}  | {{reason}}"
    }
   ]
  },
  {
   "title": "Embeddings - NLP Embedding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Embeddings Score latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_score_embeddings_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, language))",
       "legendFormat": "80th | {{language}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_nlp_orchestrator_score_embeddings_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, language))",
       "legendFormat": "90th | {{language}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_score_embeddings_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, language))",
       "legendFormat": "99th | {{language}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Keyphrases - NLP Matcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keyphrases Score Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_score_keyphrases_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_score_keyphrases_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_score_keyphrases_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Keyphrases Train Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_train_keyphrases_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_train_keyphrases_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_train_keyphrases_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Keyphrase Score Timeouts / min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_nlp_orchestrator_score_keyphrases_timeout_counter_total{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "Keyphrase Train Timeouts / min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_nlp_orchestrator_train_keyphrases_timeout_counter_total{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "Init Lexicon Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_train_init_lexicon_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "90th | {{container}}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_train_init_lexicon_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "95th | {{container}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_train_init_lexicon_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "99th | {{container}}"
      }
     ]
    },
    {
     "title": "Init Lexicon Timeouts / min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_nlp_orchestrator_train_init_lexicon_timeout_counter_total{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Timeouts"
      }
     ]
    }
   ]
  },
  {
   "title": "System Slots - NLP Ner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Slots Score Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_score_system_slots_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_score_system_slots_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_score_system_slots_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "System Slots Train Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_train_system_slots_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_train_system_slots_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_train_system_slots_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "System Slots Score Timeouts / min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_nlp_orchestrator_score_system_slots_timeout_counter_total{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Timeouts"
      }
     ]
    },
    {
     "title": "System Slots Train Timeouts / min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_nlp_orchestrator_train_system_slots_timeout_counter_total{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Timeouts"
      }
     ]
    }
   ]
  },
  {
   "title": "Classification - NLP Classifier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classifier Score Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_nlp_orchestrator_score_classifier_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_nlp_orchestrator_score_classifier_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_nlp_orchestrator_score_classifier_latency_histogram_milliseconds_bucket{cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[1m])) by (le, container))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Classifier Score Timeouts / min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(cognigy_nlp_orchestrator_score_classifier_timeout_counter_total{cluster=\"$cluster\"}[1m]))",
       "legendFormat": "Timeouts"
      }
     ]
    }
   ]
  },
  { "title": "CPU Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Orchestrator CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Orchestrator CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-orchestrator\", }[$__rate_interval]) / increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", container=~\"service-nlp-orchestrator\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\",}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    }
   ]
  },
  { "title": "Memory Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Orchestrator Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"service-nlp-orchestrator\", workload_type=\"$type\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", job=\"kube-state-metrics\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=~\"service-nlp-orchestrator\"}\n) by (pod)\n"
    }
   ]
  }
 ]
}