{
 "title": "Service-Handover",
 "description": "Service-Handover metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(cognigy_http_request_duration_count{cluster=\"$cluster\"},route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Handover External HTTP Requests / min ",
   "type": "timeseries",
   "description": "Handover External HTTP Requests /min Rate filter by route (provider) ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(cognigy_http_request_duration_count{cluster=\"$cluster\", container=\"service-handover\", route=~\"$route\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Handover External HTTP Requests Latency",
   "type": "timeseries",
   "description": "Handover External HTTP Requests Latency filter by route (provider) ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_http_request_duration_bucket{cluster=\"$cluster\", container=\"service-handover\", route=~\"$route\"}[1m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_http_request_duration_bucket{cluster=\"$cluster\", container=\"service-handover\", route=~\"$route\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_http_request_duration_bucket{cluster=\"$cluster\", container=\"service-handover\", route=~\"$route\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_http_request_duration_bucket{cluster=\"$cluster\", container=\"service-handover\", route=~\"$route\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Handover External HTTP Requests Latency",
   "type": "heatmap",
   "description": "Handover External HTTP Requests Latency filtered by route (provider)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cognigy_http_request_duration_bucket{cluster=\"$cluster\", container=\"service-handover\", route=~\"$route\"}[1m]))",
     "legendFormat": "{{le}}:{{route}}"
    }
   ]
  },
  {
   "title": "Handover RPC Requests / min ",
   "type": "timeseries",
   "description": "Handover internal RPC Requests (handover-rpc-queue) / min rate by request type ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (increase(cognigy_services_histogram_rpc_execution_time_count{cluster=\"$cluster\", queue=\"handover-rpc-queue\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Handover RPC Requests Latency",
   "type": "timeseries",
   "description": "Handover internal RPC Requests Latency",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_services_histogram_rpc_execution_time_bucket{cluster=\"$cluster\", queue=\"handover-rpc-queue\",type=\"requestHandover\"}[1m])) by (le))",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_services_histogram_rpc_execution_time_bucket{cluster=\"$cluster\", queue=\"handover-rpc-queue\",type=\"requestHandover\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_services_histogram_rpc_execution_time_bucket{cluster=\"$cluster\", queue=\"handover-rpc-queue\",type=\"requestHandover\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_services_histogram_rpc_execution_time_bucket{cluster=\"$cluster\", queue=\"handover-rpc-queue\",type=\"requestHandover\"}[1m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}