{
 "title": "AI / Service AI",
 "tags": [
  "cognigy",
  "cognigy.ai"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uncaught errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_ai_uncaught_error_total{cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Session state persistence errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cognigy_ai_session_state_persist_error_total{cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Handover errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_ai_handover_error_amount{cluster=\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Message rate per minute (per AI replica)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(cognigy_ai_message_processing_time_count{cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory related information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total in-memory brain count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cognigy_ai_brain_in_memory_count{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Number of in-memory brains (per AI replica)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cognigy_ai_brain_in_memory_count{cluster=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Garbage collector activity  service-ai",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (kind)(rate(nodejs_gc_duration_seconds_sum{cluster=\"$cluster\", container=\"service-ai\"}[5m])) / sum by (kind)(rate(nodejs_gc_duration_seconds_count{cluster=\"$cluster\", container=\"service-ai\"}[5m]))",
       "legendFormat": "{{kind}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Flow execution time (only chart execution)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_ai_flow_execution_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_ai_flow_execution_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_flow_execution_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_ai_flow_execution_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Message execution time (full receive message)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_ai_message_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_ai_message_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_message_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_ai_message_processing_time_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "99th"
      }
     ]
    },
    {
     "title": "Message Stack Latency",
     "type": "timeseries",
     "description": "Latency of the Cognigy.AI message stack (seconds).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.80, sum(rate(cognigy_ai_message_stack_latency_bucket{cluster=\"$cluster\"}[5m])) by (le)) / 1000",
       "legendFormat": "80th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(cognigy_ai_message_stack_latency_bucket{cluster=\"$cluster\"}[5m])) by (le)) / 1000",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_ai_message_stack_latency_bucket{cluster=\"$cluster\"}[5m])) by (le)) / 1000",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cognigy_ai_message_stack_latency_bucket{cluster=\"$cluster\"}[5m])) by (le)) / 1000",
       "legendFormat": "99th"
      }
     ]
    }
   ]
  },
  {
   "title": "Contact Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Contact Profile persisting count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(cognigy_ai_contact_profile_persist_count{cluster=\"$cluster\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "SMTP Emails related Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "SMTP Emails Sent (per AI replica)",
   "type": "timeseries",
   "description": "The total amount of SMTP Emails sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_ai_send_smtp_emails_count{cluster=\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SMTP Email Errors (per AI replica)",
   "type": "timeseries",
   "description": "The total amount of failing SMTP Email requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_ai_send_smtp_emails_error_count{cluster=\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Dead-lettered Messages Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Dead-lettered Messages (per AI replica)",
   "type": "timeseries",
   "description": "The total amount of dead-lettered Messages",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(cognigy_ai_expired_messages_count{cluster=\"$cluster\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}