{
 "title": "AI / Simulator",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Availability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_service_healthy{cluster=\"$cluster\", container=\"service-testing\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Availability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_dependency_rabbitmq_available{cluster=\"$cluster\", container=\"service-testing\"}) by (container)",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "sum(cognigy_dependency_redis_available{cluster=\"$cluster\", container=\"service-testing\"}) by (container)",
     "legendFormat": "Redis"
    },
    {
     "expr": "sum(cognigy_dependency_mongodb_available{cluster=\"$cluster\", container=\"service-testing\"}) by (container)",
     "legendFormat": "Mongodb"
    }
   ]
  },
  {
   "title": "Creation Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total simulations Created per project",
     "type": "table",
     "description": "Total Count of simulations Created per project",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(cognigy_service_testing_simulations_created_total{cluster=\"$cluster\"}) by (projectId, organisationId)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Persona Generation Counter",
     "type": "table",
     "description": "Count of Persona Generations",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
     "targets": [
      {
       "expr": "sum(cognigy_service_testing_persona_generations_total{cluster=\"$cluster\", container=\"service-testing\"}) by (status, organisationId, projectId)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Simulation Batches Created by Status, projectId",
     "type": "timeseries",
     "description": "Count of Simulation Batches Created by simulationBatchstatus",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(cognigy_service_testing_simulation_batches_total{cluster=\"$cluster\"}) by (projectId, simulationBatchstatus)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Simulation Runs Counter",
     "type": "timeseries",
     "description": "Count of Simulation runs",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(cognigy_service_testing_simulation_runs_total{cluster=\"$cluster\", container=\"service-testing\"})",
       "legendFormat": "Simulation Runs Total"
      },
      {
       "expr": "sum(cognigy_service_testing_simulation_runs_total{cluster=\"$cluster\", simulationStatus=\"SUCCESS\"}) by (simulationStatus)",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(cognigy_service_testing_simulation_runs_total{cluster=\"$cluster\", simulationStatus=\"FAILED\"}) by (simulationStatus)",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Incoming Requests by Method Counter",
     "type": "timeseries",
     "description": "Total Incoming Requests by Method ",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\"})",
       "legendFormat": "Total Requests"
      },
      {
       "expr": "sum by (endpoint_group, method) (\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$\"},\n    \"endpoint_group\", \"/simulations/*/batches/*/runs\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches(?:/.*)?$\"},\n    \"endpoint_group\", \"/simulations/*/batches\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/schedule$\"},\n    \"endpoint_group\", \"/simulations/*/schedule\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/?$\"},\n    \"endpoint_group\", \"/simulations/*\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/?$\"},\n    \"endpoint_group\", \"/simulations/\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/batches$\"},\n    \"endpoint_group\", \"/simulations/batches\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{\n      cluster=\"$cluster\", container=\"service-testing\",\n      exported_endpoint!~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$|^/simulations/[^/]+/batches(?:/.*)?$|^/simulations/[^/]+/schedule$|^/simulations/[^/]+/?$|^/simulations/?$|^/simulations/batches$\"\n    },\n    \"endpoint_group\", \"$1\", \"exported_endpoint\", \"(.*)\"\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Taken by Incoming Requests",
     "type": "heatmap",
     "description": "Time Taken by Incoming Requests",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(le) (rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average API Response Time by Endpoint",
     "type": "timeseries",
     "description": "This chart shows the average response time for API requests, grouped by endpoint.\n\n- The average is calculated by dividing the total time spent serving requests by the total number of requests for each base URL, over the selected time range.\n- Use this chart to identify which API endpoints are slower on average and may need optimization.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n  sum by (endpoint_group, method) (\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/batches/*/runs\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches(?:/.*)?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/batches\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/schedule$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/schedule\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/batches$\"}[5m]),\n      \"endpoint_group\", \"/simulations/batches\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_sum{\n        cluster=\"$cluster\", container=\"service-testing\",\n        exported_endpoint!~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$|^/simulations/[^/]+/batches(?:/.*)?$|^/simulations/[^/]+/schedule$|^/simulations/[^/]+/?$|^/simulations/?$|^/simulations/batches$\"\n      }[5m]),\n      \"endpoint_group\", \"$1\", \"exported_endpoint\", \"(.*)\"\n    )\n  )\n)\n/\n(\n  sum by (endpoint_group, method) (\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/batches/*/runs\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches(?:/.*)?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/batches\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/schedule$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/schedule\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/batches$\"}[5m]),\n      \"endpoint_group\", \"/simulations/batches\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_count{\n        cluster=\"$cluster\", container=\"service-testing\",\n        exported_endpoint!~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$|^/simulations/[^/]+/batches(?:/.*)?$|^/simulations/[^/]+/schedule$|^/simulations/[^/]+/?$|^/simulations/?$|^/simulations/batches$\"\n      }[5m]),\n      \"endpoint_group\", \"$1\", \"exported_endpoint\", \"(.*)\"\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Response Time Percentiles",
     "type": "timeseries",
     "description": "This chart displays the response time percentiles (P50, P90, P95, P99) for API requests.\n- P50 (Median): 50% of requests are faster than this value (typical user experience).\n- P90: 90% of requests are faster than this value (shows \"tail\" latency).\n- P95: 95% of requests are faster than this value (captures more outliers).\n- P99: 99% of requests are faster than this value (shows rare, slowest requests).\n",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (endpoint_group, method, le) (\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/batches/*/runs\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/batches(?:/.*)?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/batches\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+/schedule$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*/schedule\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/[^/]+$\"}[5m]),\n      \"endpoint_group\", \"/simulations/*\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/?$\"}[5m]),\n      \"endpoint_group\", \"/simulations/\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{cluster=\"$cluster\", container=\"service-testing\", exported_endpoint=~\"^/simulations/batches$\"}[5m]),\n      \"endpoint_group\", \"/simulations/batches\", \"exported_endpoint\", \".*\"\n    )\n  or\n    label_replace(\n      rate(cognigy_service_testing_api_request_duration_seconds_bucket{\n        cluster=\"$cluster\", container=\"service-testing\",\n        exported_endpoint!~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$|^/simulations/[^/]+/batches(?:/.*)?$|^/simulations/[^/]+/schedule$|^/simulations/[^/]+$|^/simulations/?$|^/simulations/batches$\"\n      }[5m]),\n      \"endpoint_group\", \"$1\", \"exported_endpoint\", \"(.*)\"\n    )\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Taken by Simulation Runs (95th percentile)",
     "type": "timeseries",
     "description": "95% of the simulations runs are faster (took less time) than the given time",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(cognigy_service_testing_simulation_run_duration_seconds_bucket{cluster=\"$cluster\"}[5m])))",
       "legendFormat": "95th"
      }
     ]
    },
    {
     "title": "Error Rate per endpoint, status code",
     "type": "bargauge",
     "description": "Count of 4xx and 5xx responses per minute",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (statusCode, endpoint_group) (\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", statusCode=~\"4..|5..\", exported_endpoint=~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$\"},\n    \"endpoint_group\", \"/simulations/*/batches/*/runs\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", statusCode=~\"4..|5..\", exported_endpoint=~\"^/simulations/[^/]+/batches(?:/.*)?$\"},\n    \"endpoint_group\", \"/simulations/*/batches\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", statusCode=~\"4..|5..\", exported_endpoint=~\"^/simulations/[^/]+/schedule$\"},\n    \"endpoint_group\", \"/simulations/*/schedule\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", statusCode=~\"4..|5..\", exported_endpoint=~\"^/simulations/[^/]+/?$\"},\n    \"endpoint_group\", \"/simulations/*\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", statusCode=~\"4..|5..\", exported_endpoint=~\"^/simulations/?$\"},\n    \"endpoint_group\", \"/simulations/\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{cluster=\"$cluster\", statusCode=~\"4..|5..\", exported_endpoint=~\"^/simulations/batches$\"},\n    \"endpoint_group\", \"/simulations/batches\", \"exported_endpoint\", \".*\"\n  )\nor\n  label_replace(\n    cognigy_service_testing_api_requests_total{\n      cluster=\"$cluster\", statusCode=~\"4..|5..\",\n      exported_endpoint!~\"^/simulations/[^/]+/batches/[^/]+/runs(?:/.*)?$|^/simulations/[^/]+/batches(?:/.*)?$|^/simulations/[^/]+/schedule$|^/simulations/[^/]+/?$|^/simulations/?$|^/simulations/batches$\"\n    },\n    \"endpoint_group\", \"$1\", \"exported_endpoint\", \"(.*)\"\n  )\n)",
       "legendFormat": "{{statusCode}} - {{endpoint_group}}"
      }
     ]
    },
    {
     "title": "Total runs per turn range",
     "type": "bargauge",
     "description": "Total runs per turn range",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cognigy_service_testing_simulation_run_duration_seconds_count{cluster=\"$cluster\",container=\"service-testing\"}) by (turnRange)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Playbook Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simulation Play success Counter",
     "type": "table",
     "description": "Counts the total number of times the simulation player simulation success",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_simulation_success{cluster=\"$cluster\"}) by (simulationReference, simulationRunBatchReference)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Manual stop batch Counter",
     "type": "table",
     "description": "Counts the total number of times the simulation player's manual stop batch",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_simulation_manual_stop_batch{cluster=\"$cluster\"}) by (simulationReference, simulationRunBatchReference)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LLM Error Counter",
     "type": "table",
     "description": "Counts the total number of times the simulation player llm error",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_simulation_llm_error{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Final Ping Timeout Counter",
     "type": "table",
     "description": "Counts the total number of times the simulation player final ping timeout is reached",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_simulation_final_ping_timeout{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Agent replay no output Counter",
     "type": "table",
     "description": "Counts the total number of times the simulation player agent replay no outputs",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_simulation_agent_replay_no_outputs{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dead lettered messages on endpoint Counter",
     "type": "table",
     "description": "Counts the total number of Simulation dead lettered messages on endpoint",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_simulation_dead_lettered_messages{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Simulation Duration per project",
     "type": "timeseries",
     "description": "This chart shows how long playbook simulations take to complete over time, broken down by percentiles:\n\n• P50 (Median) - Half of all simulations finish faster than this time\n• P95 - 95% of simulations finish faster than this time  \n• P99 - 99% of simulations finish faster than this time",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_playbook_execution_simulation_duration_bucket{cluster=\"$cluster\"}[5m])) by (le, projectId, organisationId))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Simulation Turn Duration per project",
     "type": "timeseries",
     "description": "This chart shows how long playbook simulation turns take to complete over time, broken down by percentiles:\n\n• P50 (Median) - Half of all simulation turns finish faster than this time\n• P95 - 95% of simulation turns finish faster than this time  \n• P99 - 99% of simulation turns finish faster than this time",
     "gridPos": { "h": 12, "w": 11, "x": 13, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_playbook_execution_simulation_turn_duration_bucket{cluster=\"$cluster\"}[5m])) by (le, projectId, organisationId))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Evaluation Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Evaluation Profiles Status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(cognigy_playbook_execution_evaluation_profiles_total{cluster=\"$cluster\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Evaluation Profile Duration (p50/p95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 46 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(cognigy_playbook_execution_evaluation_profile_duration_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_playbook_execution_evaluation_profile_duration_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Evaluation Batch Duration (p95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 46 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(cognigy_playbook_execution_evaluation_batch_duration_bucket{cluster=\"$cluster\"}[5m])) by (le))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Evaluation Criteria by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum(increase(cognigy_playbook_execution_evaluation_criteria_total{cluster=\"$cluster\"}[5m])) by (criterion_type)",
       "legendFormat": "{{criterion_type}}"
      }
     ]
    },
    {
     "title": "Evaluation Token Spend",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum(increase(cognigy_playbook_execution_evaluation_tokens_total{cluster=\"$cluster\"}[5m])) by ()",
       "legendFormat": "Total Tokens"
      }
     ]
    }
   ]
  }
 ]
}