{
 "title": "xApps Metrics",
 "description": "Dashboard for xApps metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Current Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Counter for last 24 Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(cognigy_app_session_manager_initialized_app_sessions_count[24h]))",
     "legendFormat": "Initialized Sessions"
    },
    {
     "expr": "sum(max_over_time(cognigy_app_session_manager_first_app_session_connections_count[24h]))",
     "legendFormat": "First Time Connected Sessions"
    },
    {
     "expr": "sum(max_over_time(cognigy_app_session_manager_first_app_submits_count[24h]))",
     "legendFormat": "First Time Submitted Sessions"
    }
   ]
  },
  {
   "title": "Total number of intialized sessions in selected range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(cognigy_app_session_manager_initialized_app_sessions_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of first time connections in selected range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(cognigy_app_session_manager_first_app_session_connections_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio of initialized, connected and submitted sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(cognigy_app_session_manager_initialized_app_sessions_count)",
     "legendFormat": "Initialized Sessions"
    },
    {
     "expr": "sum(cognigy_app_session_manager_first_app_session_connections_count)",
     "legendFormat": "First Time Connected Sessions"
    },
    {
     "expr": "sum(cognigy_app_session_manager_first_app_submits_count)",
     "legendFormat": "First Time Submitted Sessions"
    }
   ]
  },
  {
   "title": "Total number of first time submitted sessions in selected range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(cognigy_app_session_manager_first_app_submits_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OrganizationID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of intialized sessions grouped by organizationId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(organisationId) (cognigy_app_session_manager_initialized_app_sessions_count)",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Number of  first time session connections grouped by organizationId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(organisationId) (cognigy_app_session_manager_first_app_session_connections_count)",
     "legendFormat": "{{organisationId}}"
    }
   ]
  },
  {
   "title": "Number of first app submits grouped by organizationId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "sum by(organisationId) (cognigy_app_session_manager_first_app_submits_count)",
     "legendFormat": "{{organisationId}}"
    }
   ]
  }
 ]
}