{
 "title": "Agent Assist Frontend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error while retrieving AAW session params",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_frontend_session_params_retrieval_error_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TCP Socket count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_assist_frontend_tcp_socket_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connections per AAW FE replica",
   "type": "timeseries",
   "description": "Number of open TCP connections per agent-assist-frontend replica",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "agent_assist_frontend_tcp_socket_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}