{
 "title": "Agent Assist Backend",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent Assist Sessions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_agent_assist_session_count[1m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tile Updates Overview",
   "type": "timeseries",
   "description": "This panel shows the total number of tile updates for the card, HTML, Iframe, and transcript tiles over time, with data displayed for the last hour.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "increase(agent_assist_backend_tile_update_count{type=\"card\"}[1h])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "increase(agent_assist_backend_tile_update_count{type=\"iframe\"}[1h])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "increase(agent_assist_backend_tile_update_count{type=\"html\"}[1h])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "increase(agent_assist_backend_tile_update_count{type=\"transcript\"}[1h])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Iframe tile updates count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_tile_update_count{type=\"iframe\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTML tile updates count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_tile_update_count{type=\"html\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Card  tile updates count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_tile_update_count{type=\"card\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transcript  tile updates count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_tile_update_count{type=\"transcript\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncaught errors",
   "type": "timeseries",
   "description": "Number of uncaught errors in agent-assit-backend microservice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_frontend_uncaught_error_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error while retrieving AAW config",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_config_retrieval_error_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error while retrieving AAW session params",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(agent_assist_backend_session_params_retrieval_error_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "TCP Socket count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_assist_backend_tcp_socket_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connections per AAW BE replica",
   "type": "timeseries",
   "description": "Number of open TCP connections per agent-assist-backend replica",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "agent_assist_backend_tcp_socket_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}