{
 "title": "AI Copilot / Genesys Notifications Forwarder",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Websocket connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_open_websocket_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total WebSocket error messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_forwarded_websocket_message_failed_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Added Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_added_subscriptions_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total WebSocket messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_websocket_message_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Forwarded WebSocket messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_forwarded_websocket_message_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Assist Genesys Notifications Forwarder Uncaught Error Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_uncaught_error_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genesys Subscribe To Topics Job Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(genesys_subscribe_to_topics_job_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Cache Manager Get Entries Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(channel_cache_manager_get_entries_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Cache Manager Failed Operations Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(channel_cache_manager_failed_operations_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Cache Manager Update Entry Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(channel_cache_manager_update_entry_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genesys Update Entry In Redis Cache Job Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(genesys_update_entry_in_redis_cache_job_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genesys Login Resubscribe Job Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(genesys_login_resubscribe_job_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Genesys Remove Old Topics Job Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(genesys_remove_old_topics_job_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Cache Manager Add Entry Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(channel_cache_manager_add_entry_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Cache Manager Delete Entry Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(channel_cache_manager_delete_entry_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "TCP Socket count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_assist_genesys_notifications_forwarder_tcp_socket_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connections per AAW GNF replica",
   "type": "timeseries",
   "description": "Number of open TCP connections per agent-assist-genesys-notifications-forwarder replica",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "agent_assist_genesys_notifications_forwarder_tcp_socket_count{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}