{
 "title": "Live Agent Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Accounts Endpoints Status Codes",
   "type": "piechart",
   "description": "Accounts endpoints and its status codes. More information at the Live Agent OpenAPI definitions",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"api/v1/accounts\"})",
     "legendFormat": "{{action}} {{ controller }} {{ status }}"
    }
   ]
  },
  {
   "title": "Inbox Endpoints Status Codes",
   "type": "piechart",
   "description": "Inboxes endpoints and its status codes. More information at the Live Agent OpenAPI definitions",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"api/v1/accounts/inboxes\"})",
     "legendFormat": "{{action}} {{ controller }} {{ status }}"
    }
   ]
  },
  {
   "title": "Conversation Endpoints Status Codes",
   "type": "piechart",
   "description": "Conversations endpoints and its status codes. More information at the Live Agent OpenAPI definitions",
   "gridPos": { "h": 13, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"api/v1/accounts/conversations\"})",
     "legendFormat": "{{action}} {{ controller }} {{ status }}"
    }
   ]
  },
  {
   "title": "Contacts Endpoint Status Codes",
   "type": "piechart",
   "description": "Contacts endpoints and its status codes. More information at the Live Agent OpenAPI definitions",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"api/v1/accounts/contacts\"})",
     "legendFormat": "{{action}} {{ controller }} {{ status }}"
    }
   ]
  },
  {
   "title": "Messages  Endpoints Status Codes",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"api/v1/accounts/conversations/messages\"})",
     "legendFormat": "{{action}} {{controller}} {{status}}"
    }
   ]
  },
  {
   "title": "Agent Bot  Platform Endpoints Status Codes",
   "type": "piechart",
   "description": "Agent Bot that is created into Live Agent. This happens when the handover process happens",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"platform/api/v1/agent_bots\"})",
     "legendFormat": "{{action}} {{ controller }} {{ status }}"
    }
   ]
  },
  {
   "title": "Old Agent Bot Endpoints Status Codes",
   "type": "piechart",
   "description": "Agent Bot that is created into Live Agent. This happens when the handover process happens",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action, controller, status) (ruby_http_requests_total{cluster=\"$cluster\", controller=\"api/v1/accounts/agent_bots\"})",
     "legendFormat": "{{action}} {{ controller }} {{ status }}"
    }
   ]
  },
  {
   "title": "Total Requests per Status Code",
   "type": "stat",
   "description": "Total Requests per Status Code within the specified interval",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(ruby_http_requests_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests over 1min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (status, method, action, controller) (increase(ruby_http_requests_total{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\"}[1m]))",
     "legendFormat": "{{method}} {{status}} {{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "api/v1/accounts/ Error Rate (%)",
   "type": "timeseries",
   "description": "percentage of error rate for api/v1/accounts/ endpoint",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "100*sum(rate(ruby_http_requests_total{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\", status!~\"2..|3..|404\"}[1m])) by (action, controller, status) /sum(rate(ruby_http_requests_total{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\"}[1m])) by (action, controller, status)",
     "legendFormat": "{{status}} {{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "4xx/5xx Error Rate by Endpont",
   "type": "timeseries",
   "description": "4xx/5xx Errors per minute",
   "gridPos": { "h": 16, "w": 12, "x": 11, "y": 34 },
   "targets": [
    {
     "expr": "sum by (status, controller) (increase(ruby_http_requests_total{cluster=\"$cluster\", status=~\"4..|5..\"}[1m]))",
     "legendFormat": "{{status}} {{controller}} "
    }
   ]
  },
  {
   "title": "Endpoint latency (99th percentile)",
   "type": "timeseries",
   "description": "99th percentile of Endpoint response time ",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (ruby_http_request_duration_seconds{cluster=\"$cluster\", controller=~'api/v1/accounts.*', quantile='0.99'}) by (controller, action) \t\t",
     "legendFormat": "{{controller}}/{{action}} (99th percentile)"
    }
   ]
  },
  {
   "title": "Top Endpoints By Request Count",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (action, controller) (increase(ruby_http_requests_total{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\"}[1m]))\t",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Top Endpoints by Latency",
   "type": "table",
   "description": "Average latency per controller over the specified interval",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg (ruby_http_request_duration_seconds{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\", quantile='0.99'}) by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (ruby_http_request_duration_seconds{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\", quantile='0.9'})  by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg (ruby_http_request_duration_seconds{cluster=\"$cluster\", controller=~\"api/v1/accounts/.*\", quantile='0.5'}) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}