{
 "title": "LA / OData Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(live_agent_odata_hits_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total hits by model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(model) (rate(live_agent_odata_hits_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncaught errors",
   "type": "timeseries",
   "description": "Number of uncaught errors in Live Agent OData microservice",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(live_agent_odata_uncaught_error_total{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}