{
 "title": "Analytics Conversations",
 "description": "Service Analytics Conversations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Conversations",
   "type": "stat",
   "description": "Number of New Conversations Records Inserted",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_analytics_conversations_stored_conversations_records_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conversations Records Deleted",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (projectId) (cognigy_analytics_conversations_deleted_conversations_records_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Analytics Conversations Error Counts",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(cognigy_analytics_conversations_format_error_conversations_total[24h])))",
     "legendFormat": "Format Conversations"
    },
    {
     "expr": "round(sum(increase(cognigy_analytics_conversations_insert_error_conversations_total[24h])))",
     "legendFormat": "Conversations Records Insert"
    },
    {
     "expr": "round(sum(increase(cognigy_analytics_conversations_generate_transcripts_report_error_total[24h])))",
     "legendFormat": "Generate Transcript Report"
    },
    {
     "expr": "round(sum(increase(cognigy_analytics_conversations_generate_messages_report_error_total[24h])))",
     "legendFormat": "Generate Messages Report"
    }
   ]
  },
  {
   "title": "Time to Generate Transcript Report",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_analytics_conversations_generate_transcripts_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_analytics_conversations_generate_transcripts_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_analytics_conversations_generate_transcripts_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_analytics_conversations_generate_transcripts_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to Generate Message Report",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_analytics_conversations_generate_messages_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_analytics_conversations_generate_messages_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_analytics_conversations_generate_messages_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_analytics_conversations_generate_messages_report_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}