{
 "title": "Analytics Odata",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total number of incoming find requests for each report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gauge of incoming find requests for a specific collection",
     "type": "gauge",
     "description": "Gauge of incoming find requests for a specific collection",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (odataCollectionName) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by Collection",
     "type": "piechart",
     "description": "Pie chart of incoming find requests by collection",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (odataCollectionName)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by Host",
     "type": "timeseries",
     "description": "Incoming Find Requests by Host",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (host)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by Collection and Method",
     "type": "table",
     "description": "Table of incoming find requests by collection and method",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (odataCollectionName, method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Incoming Find Requests",
     "type": "stat",
     "description": "Total Incoming Find Requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by URL",
     "type": "timeseries",
     "description": "Incoming Find Requests by URL",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": " sum(cognigy_analytics_odata_incoming_find_requests_counter) by (url)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by Collection",
     "type": "timeseries",
     "description": "Stacked area graph of incoming find requests by collection",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (odataCollectionName)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by Method",
     "type": "timeseries",
     "description": "Incoming Find Requests by Method",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming Find Requests by Collection",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(cognigy_analytics_odata_incoming_find_requests_counter) by (odataCollectionName)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "The amount of time it took to finish odata pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "average time taken to finish the odata pipeline",
   "type": "bargauge",
   "description": " This graph shows the average time taken to finish the odata pipeline for each collections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cognigy_analytics_odata_run_odata_pipeline_time_sum) by (odataCollectionName) / avg(cognigy_analytics_odata_run_odata_pipeline_time_count) by (odataCollectionName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time taken to finish the odata pipeline for all collections",
   "type": "table",
   "description": "This graph shows the average time taken to finish the odata pipeline for all collections, along with the number of samples.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "avg(cognigy_analytics_odata_run_odata_pipeline_time_sum) by (odataCollectionName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(cognigy_analytics_odata_run_odata_pipeline_time_count) by (odataCollectionName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken to finish the odata pipeline for both collections over time,",
   "type": "timeseries",
   "description": "This graph shows the time taken to finish the odata pipeline for all collections over time, stacked on top of each other.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (odataCollectionName) (rate(cognigy_analytics_odata_run_odata_pipeline_time_sum[5m])) / sum by (odataCollectionName) (rate(cognigy_analytics_odata_run_odata_pipeline_time_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken to finish the odata pipeline ",
   "type": "timeseries",
   "description": "Line Graph: This graph shows the time taken to finish the odata pipeline for the analytics collection over time.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(cognigy_analytics_odata_run_odata_pipeline_time_sum / cognigy_analytics_odata_run_odata_pipeline_time_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OData pipeline run time",
   "type": "histogram",
   "description": "This query calculates the 95th percentile of the OData pipeline run time for each bucket (range of time values) and each collection over the last 5 minutes.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cognigy_analytics_odata_run_odata_pipeline_time_bucket[5m])) by (le, odataCollectionName)) \n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}