{
 "title": "Analytics Collector",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Analytics Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Analytics Collector Errors",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(cognigy_analytics_collector_insert_error_analytics_total[24h])))",
     "legendFormat": "Analytics Insert Error"
    },
    {
     "expr": "round(sum(increase(cognigy_analytics_collector_format_error_analytics_total[24h])))",
     "legendFormat": "Analytics Format Error"
    },
    {
     "expr": "round(sum(increase(cognigy_analytics_collector_insert_error_sessions_total[24h])))",
     "legendFormat": "Session Insert Error"
    },
    {
     "expr": "round(sum(increase(cognigy_analytics_collector_format_error_sessions_total[24h])))",
     "legendFormat": "Session Format Error"
    }
   ]
  },
  {
   "title": "Time to Store Analytics Records",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(increase(cognigy_analytics_collector_store_analytics_records_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(increase(cognigy_analytics_collector_store_analytics_records_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(cognigy_analytics_collector_store_analytics_records_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(cognigy_analytics_collector_store_analytics_records_time_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Incoming Analytics Records",
   "type": "timeseries",
   "description": "Total no. of Analytics Records read by service-analytics-collector",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (projectId) (cognigy_analytics_collector_incoming_analytics_records_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Analytics",
   "type": "stat",
   "description": "Total no. of Analytics Records Stored in Mongo",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_analytics_collector_stored_analytics_records_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "stat",
   "description": "Number of New Sessions Records Inserted",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_analytics_collector_stored_sessions_records_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analytics Records Deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (projectId) (cognigy_analytics_collector_deleted_analytics_records_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sessions Records Deleted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (projectId) (cognigy_analytics_collector_deleted_sessions_records_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}