{
 "title": "Insights Cube Reports",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Report Generation Time Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cognigy_insights_api_generate_cube_report_time_sum[5m]) / rate(cognigy_insights_api_generate_cube_report_time_count[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Report Generation Time per QueryName",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (queryName) (cognigy_insights_api_generate_cube_report_time_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile of Report Generation Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (projectId, queryName, le) (rate(cognigy_insights_api_generate_cube_report_time_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Report Generations ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (projectId, queryName) (cognigy_insights_api_generate_cube_report_time_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Report Generation Time Per Query Name",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (projectId, queryName) (cognigy_insights_api_generate_cube_report_time_sum) / sum by (projectId, queryName) (cognigy_insights_api_generate_cube_report_time_count)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Report Generation Time per Project",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (projectId) (cognigy_insights_api_generate_cube_report_time_sum) / sum by (projectId) (cognigy_insights_api_generate_cube_report_time_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}