{
 "title": "IN / Service Collector",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Availability",
   "type": "gauge",
   "description": "Shows whether the service is healthy based on connectivity to dependencies. Displays 1 if healthy and 0 if not.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_service_healthy{cluster=\"$cluster\", container=\"service-collector\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Availability",
   "type": "gauge",
   "description": "Availability of RebbitMQ, Redis, MongoDb",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cognigy_dependency_rabbitmq_available{cluster=\"$cluster\", container=\"service-collector\"}) by (container)",
     "legendFormat": "RabbitMQ"
    },
    {
     "expr": "sum(cognigy_dependency_redis_available{cluster=\"$cluster\", container=\"service-collector\"}) by (container)",
     "legendFormat": "Redis"
    },
    {
     "expr": "sum(cognigy_dependency_mongodb_available{cluster=\"$cluster\", container=\"service-collector\"}) by (container)",
     "legendFormat": "MongoDb"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "piechart",
   "description": "Shows total Insights, Liveagent, milestone, VG endpoints for that cluster",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, route, status_code) (cognigy_collector_http_requests_total{cluster=\"$cluster\", route=\"/v1.0/liveagent/insights\"})",
     "legendFormat": "Liveagent"
    },
    {
     "expr": "sum by(method, route, status_code) (cognigy_collector_http_requests_total{cluster=\"$cluster\", route=\"/v1.0/insights/\"})",
     "legendFormat": "Insights"
    },
    {
     "expr": "sum by(method, route, status_code) (cognigy_collector_http_requests_total{cluster=\"$cluster\", route=\"/v1.0/milestone/insights\"})",
     "legendFormat": "Milestone"
    },
    {
     "expr": "sum by(method, route, status_code) (cognigy_collector_http_requests_total{cluster=\"$cluster\", route=\"/v1.0/vg/insights\"})",
     "legendFormat": "VG"
    }
   ]
  },
  {
   "title": "Incoming vs Processed Analytics Records",
   "type": "barchart",
   "description": "Compare the rate of incoming analytics records against the rate of processed analytics records. This helps in understanding the processing rate compared to the incoming rate.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (container) (rate(cognigy_collector_incoming_analytics_records_total{cluster=\"$cluster\"}[1m])*60)",
     "legendFormat": "Incoming Analytics Records"
    },
    {
     "expr": "sum by (container) (rate(cognigy_collector_processed_analytics_records_total{cluster=\"$cluster\"}[1m])*60)",
     "legendFormat": "Processed Analytics Records"
    }
   ]
  },
  {
   "title": "Total Incoming Records",
   "type": "timeseries",
   "description": "Total no. of Analytics, Liveagent, vg, goals v2 Records read by service-collector",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(cognigy_collector_incoming_analytics_records_total{cluster=\"$cluster\"}[1m])*60)",
     "legendFormat": "Analytics Records"
    },
    {
     "expr": "sum(rate(cognigy_collector_incoming_liveagentescalations_records_total{cluster=\"$cluster\"}[1m])*60)",
     "legendFormat": "Liveagent Escalations"
    },
    {
     "expr": "sum(rate(cognigy_collector_incoming_voicegatewayevents_records_total{cluster=\"$cluster\"}[1m])*60)",
     "legendFormat": "Voice Gateway events"
    },
    {
     "expr": "sum(rate(cognigy_collector_incoming_goals_v2_records_total{cluster=\"$cluster\"}[1m])*60)",
     "legendFormat": "Goals v2"
    }
   ]
  },
  {
   "title": "Garbage collector activity  service-collector",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (kind)(rate(nodejs_gc_duration_seconds_sum{cluster=\"$cluster\", container=\"service-collector\"}[5m])) / sum by (kind)(rate(nodejs_gc_duration_seconds_count{cluster=\"$cluster\", container=\"service-collector\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Incoming requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "HTTP requests by Status Code",
   "type": "timeseries",
   "description": "Displays the HTTP Requests over time by status code, route",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "round(sum by (status_code, route) (rate(cognigy_collector_http_requests_total{cluster=\"$cluster\", route=~\"/v1.0/insights/|/v1.0/liveagent/insights|/v1.0/vg/insights|/v1.0/milestone/insights\"}[10m])*600))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insights Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "round(sum by(method, route, status_code) (rate(cognigy_collector_http_requests_total{cluster=\"$cluster\",route=\"/v1.0/insights/\"}[10m])*600))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liveagent Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "round(sum by(method, route, status_code) (rate(cognigy_collector_http_requests_total{cluster=\"$cluster\",route=\"/v1.0/liveagent/insights\"}[10m])*600))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milestone Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "round(sum by(method, route, status_code) (rate(cognigy_collector_http_requests_total{cluster=\"$cluster\",route=\"/v1.0/milestone/insights\"}[10m])*600))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voice Gateway Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "round(sum by(method, route, status_code) (rate(cognigy_collector_http_requests_total{cluster=\"$cluster\",route=\"/v1.0/vg/insights\"}[10m])*600))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time taken to store records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Analytics Records Store Time",
   "type": "heatmap",
   "description": "Time taken to store analytics records",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cognigy_collector_store_analytics_records_time_bucket{cluster=\"$cluster\", container=\"service-collector\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Conversation Records Store Time",
   "type": "heatmap",
   "description": "Time taken to store conversation records",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cognigy_collector_store_conversations_records_time_bucket{cluster=\"$cluster\", container=\"service-collector\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}