{
 "title": "VG Api-Server",
 "tags": [ "vg-service" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Api Server Errors 24h",
   "type": "stat",
   "description": "All errors in the last 24 hours",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(vg_feature_server_uncaught_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path, status) (vg_api_server_http_requests_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (vg_api_server_http_requests_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of endpoints request",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(vg_api_server_http_requests_total{cluster=\"$cluster\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Count By Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (status, method, path) (vg_api_server_http_requests_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Endpoints By Response Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "topk(10, sum by (path, method) (rate(vg_api_server_http_response_time_sum{cluster=\"$cluster\"}[1h])) / sum by (path, method) (rate(vg_api_server_http_response_time_count{cluster=\"$cluster\"}[1h])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Rate By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(vg_api_server_http_requests_total{cluster=\"$cluster\", status!~\"200|201|304|404\"}[1h])) by (method, path) / sum(rate(vg_api_server_http_requests_total{cluster=\"$cluster\"}[1h])) by (method, path) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}