{
 "title": "VG / Billing App",
 "tags": [ "vg-service" ],
 "time": { "from": "2023-06-15T10:04:35.030Z", "to": "2023-06-16T10:04:35.030Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Billing App Errors 24h",
   "type": "stat",
   "description": "All errors in the last 24 hours",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(vg_billing_app_uncaught_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "Uncaught Errors"
    },
    {
     "expr": "round(sum(increase(vg_billing_app_influxdb_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "InfluxdbErrors"
    }
   ]
  },
  { "title": "Billing App Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Endpoints Update Errors (Jobs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(vg_billing_app_deactivate_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "Deactivate Error"
    },
    {
     "expr": "sum(sum_over_time(vg_billing_app_update_call_history_error_total{cluster=\"$cluster\"}[24h]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Data Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "round(sum(increase(vg_billing_app_get_app_call_counts_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "Application Error"
    },
    {
     "expr": "round(sum(increase(vg_billing_app_get_account_call_counts_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "Account Error"
    },
    {
     "expr": "round(sum(increase(vg_billing_app_get_service_provider_call_counts_error_total{cluster=\"$cluster\"}[24h])))",
     "legendFormat": "SP Error"
    }
   ]
  },
  { "title": "Endpoint Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Endpoints Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path, status) (vg_billing_app_http_requests_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (vg_billing_app_http_requests_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of endpoints request",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(vg_billing_app_http_requests_total{cluster=\"$cluster\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Count By Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (status, method, path) (vg_billing_app_http_requests_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Endpoints By Response Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(10, sum by (path, method) (rate(vg_billing_app_http_response_time_sum{cluster=\"$cluster\"}[1h])) / sum by (path, method) (rate(vg_billing_app_http_response_time_count{cluster=\"$cluster\"}[1h])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Rate By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(vg_billing_app_http_requests_total{cluster=\"$cluster\", status!~\"200|201|304|404\"}[1h])) by (method, path) / sum(rate(vg_billing_app_http_requests_total{cluster=\"$cluster\"}[1h])) by (method, path) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}