{
 "title": "VG / Drachtio Server",
 "tags": [ "cognigy.vg" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   { "name": "endpoint", "label": "Endpoint", "query": "sip-drachtio,\nfs-drachtio" },
   { "name": "pod", "label": "Pod", "query": "sbc-sip-0,sbc-sip-1" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total INVITES",
   "type": "stat",
   "description": "Total amount of INVITES",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "floor($A /2)", "type": "math" }
   ]
  },
  {
   "title": "Stable Dialogs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(drachtio_stable_dialogs{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    { "expression": "floor($A / 2)", "type": "math" }
   ]
  },
  { "title": "Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "IN Requests/min Rate",
   "type": "timeseries",
   "description": "Incoming requests per second over the last minute",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (increase(drachtio_sip_requests_in_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IN Responses/min Rate",
   "type": "timeseries",
   "description": "Incoming responses per second over the last minute",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (increase(drachtio_sip_responses_in_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SIP Requests In",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(drachtio_sip_requests_in_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SIP Responses In",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(drachtio_sip_responses_in_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outgoing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "OUT Requests/min Rate",
   "type": "timeseries",
   "description": "Outgoing requests per second over the last minute",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (method) (increase(drachtio_sip_requests_out_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OUT Responses/min Rate",
   "type": "timeseries",
   "description": "Outgoing responses per second over the last minute",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (method) (increase(drachtio_sip_responses_out_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SIP Requests Out",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(drachtio_sip_requests_in_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SIP Responses Out",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(drachtio_sip_responses_out_total{endpoint=\"$endpoint\", pod=~\"$pod\", cluster=\"$cluster\"}[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}