{
 "title": "VG Feature-Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Feature Server Errors 24h",
   "type": "stat",
   "description": "All errors in the last 24 hours",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(vg_feature_server_uncaught_error_total[24h])))",
     "legendFormat": "Uncaught Errors"
    },
    {
     "expr": "round(sum(increase(vg_feature_server_handover_error_total[24h])))",
     "legendFormat": "Handover Errors"
    },
    {
     "expr": "round(sum(increase(vg_feature_server_analytics_schema_error_total[24h])))",
     "legendFormat": "Analytics Schema Errors"
    },
    {
     "expr": "round(sum(increase(vg_feature_server_analytics_process_command_error_total[24h])))",
     "legendFormat": "Analytics Process Command Errors"
    },
    {
     "expr": "round(sum(increase(vg_feature_server_unhandled_rejection_total[24h])))",
     "legendFormat": "Unhandled Rejections"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uncaught Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(vg_feature_server_uncaught_error_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhandled Rejections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(vg_feature_server_unhandled_rejection_total[1m]))",
     "legendFormat": "Unhandled Rejections"
    }
   ]
  },
  {
   "title": "Handover Errors",
   "type": "timeseries",
   "description": "Errors while transferring a call via sip:refer or dial\nEach status code received > 400 is counted as error",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(vg_feature_server_handover_error_total{container=\"feature-server\"}[5m])) by (type, status)",
     "legendFormat": "Type: {{type}} | Status: {{status}}"
    }
   ]
  },
  { "title": "Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Active Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vg_feature_server_call_session_count{container=\"feature-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Calls",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (vg_feature_server_call_session_count{container=\"feature-server\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory related information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage feature-server",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=\"feature-server\",workload_type=\"statefulset\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{ workload=\"feature-server\", workload_type=\"statefulset\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage collector activity feature-server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (kind)(rate(nodejs_gc_duration_seconds_sum{container=\"feature-server\"}[5m])) / sum by (kind)(rate(nodejs_gc_duration_seconds_count{container=\"feature-server\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}