{
 "title": "VG / Overview v2",
 "tags": [ "Cognigy.VG" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uncaught Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"(jambonz_api_server|sbc_rtpengine_sidecar|sbc_inbound|sbc_outbound|sbc_call_router|sbc_sip_sidecar|vg_feature_server)_uncaught_error_total\", cluster=\"$cluster\"}[1m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhandled Rejections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase({__name__=~\"(jambonz_api_server|sbc_rtpengine_sidecar|sbc_inbound|sbc_outbound|sbc_call_router|sbc_sip_sidecar|vg_feature_server)_unhandled_rejection_total\", cluster=\"$cluster\"}[1m])) by (container)",
     "legendFormat": "Unhandled Rejections"
    }
   ]
  },
  {
   "title": "Handover Errors",
   "type": "timeseries",
   "description": "Errors while transferring a call via sip:refer or dial\nEach status code received > 400 is counted as error",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(vg_feature_server_handover_error_total{cluster=\"$cluster\", container=\"feature-server\"}[5m])) by (type, status)",
     "legendFormat": "Type: {{type}} | Status: {{status}}"
    }
   ]
  },
  { "title": "Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Sessions (feature-server)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vg_feature_server_call_session_count{cluster=\"$cluster\", container=\"feature-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Calls by feature-server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (vg_feature_server_call_session_count{cluster=\"$cluster\", container=\"feature-server\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(sum by (pod) (vg_feature_server_call_session_count{cluster=\"$cluster\", container=\"feature-server\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Task Processing Time (feature-server)",
   "type": "timeseries",
   "description": "Task processing time in feature-server",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(vg_feature_server_task_duration_milliseconds{cluster=\"$cluster\"}[1m])) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Errors (feature-server)",
   "type": "timeseries",
   "description": "Errors by processed task in feature-server",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(vg_feature_server_task_error{cluster=\"$cluster\"}[1m])) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory related information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=\"feature-server\",workload_type=\"statefulset\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", workload=\"feature-server\", workload_type=\"statefulset\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Garbage collector activity feature-server",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (kind)(rate(nodejs_gc_duration_seconds_sum{cluster=\"$cluster\", container=\"feature-server\"}[5m])) / sum by (kind)(rate(nodejs_gc_duration_seconds_count{cluster=\"$cluster\", container=\"feature-server\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}