{
 "title": "VG SBC-Outbound",
 "tags": [ "vg-service" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sbc-outbound Errors 24h",
   "type": "stat",
   "description": "All errors in the last 24 hours",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(vg_feature_server_uncaught_error_total[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uncaught Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "round(sum(increase(sbc_outbound_uncaught_error_total[24h])))"
    }
   ]
  },
  {
   "title": "SBC Outbound Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pod",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sbc_sip_calls_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "direction", "operator": "=", "value": "outbound" }
     ]
    }
   ]
  }
 ]
}